/* eslint-disable */

/* tslint:disable */

// This file was generated by typedapi-client-helpers. Do not edit manually.

export interface OrderModel {
  id: string;
  orderNumber: string | null;
  productId: string;
  supplierId: string;
  quantity: number;
  totalPrice: number;
  orderedAt: string;
  status: OrderStatus;
}

export interface OrderModelApiPaginationResponse {
  data: OrderModel[] | null;
  pageNumber: number;
  pageSize: number;
  totalCount: number;
}

export interface OrderRequest {
  orderNumber: string | null;
  productId: string;
  supplierId: string;
  quantity: number;
  totalPrice: number;
  orderedAt: string;
  status: OrderStatus;
}

export type OrderStatus = "Draft" | "Pending" | "Approved" | "Shipped" | "Cancelled";

export interface ProductModel {
  id: string;
  name: string | null;
  sku: string | null;
  price: number;
  stock: number;
  active: boolean;
  supplierId: string;
  createdAt: string;
}

export interface ProductRequest {
  name: string | null;
  sku: string | null;
  price: number;
  stock: number;
  active: boolean;
  supplierId: string;
}

export interface ProductTableRow {
  id: string;
  name: string | null;
  sku: string | null;
  price: number;
  stock: number;
  active: boolean;
}

export interface ProductTableRowApiPaginationResponse {
  data: ProductTableRow[] | null;
  pageNumber: number;
  pageSize: number;
  totalCount: number;
}

export type SortDirection = "Default" | "Ascending" | "Descending";

export interface SupplierModel {
  id: string;
  companyName: string | null;
  contactEmail: string | null;
  countryCode: string | null;
  verified: boolean;
  createdAt: string;
}

export interface SupplierModelApiPaginationResponse {
  data: SupplierModel[] | null;
  pageNumber: number;
  pageSize: number;
  totalCount: number;
}

export interface SupplierRequest {
  companyName: string | null;
  contactEmail: string | null;
  countryCode: string | null;
  verified: boolean;
}

export interface UploadResult {
  fileCount: number;
  fileNames: string[] | null;
  message: string | null;
}

export interface WarehouseModel {
  id: string;
  code: string | null;
  name: string | null;
  city: string | null;
  countryCode: string | null;
  capacity: number;
  isActive: boolean;
}

export interface WarehouseModelApiPaginationResponse {
  data: WarehouseModel[] | null;
  pageNumber: number;
  pageSize: number;
  totalCount: number;
}

export interface WarehouseRequest {
  code: string | null;
  name: string | null;
  city: string | null;
  countryCode: string | null;
  capacity: number;
  isActive: boolean;
}
