/* eslint-disable */
/* tslint:disable */
// This file was generated by typedapi-client-helpers. Do not edit manually.

export type QueryValue = string | number | boolean | null | undefined | Date | QueryValue[];
export type QueryParams = Record<string, QueryValue>;

export const ContentType = {
  Json: "application/json",
  FormData: "multipart/form-data",
  UrlEncoded: "application/x-www-form-urlencoded",
  Text: "text/plain",
} as const;

export type ContentType = (typeof ContentType)[keyof typeof ContentType];

export interface HttpResponse<D extends unknown, E extends unknown = unknown> extends Response {
  data: D;
  error: E;
}

export type RequestParams = Omit<RequestInit, "body" | "method"> & {
  secure?: boolean;
  query?: QueryParams;
  pathParams?: Record<string, string | number | boolean>;
  baseUrl?: string;
};

export type ApiConfig = {
  baseUrl?: string;
  baseApiParams?: RequestParams;
  securityWorker?: (securityData: unknown) => Promise<RequestParams | void> | RequestParams | void;
  customFetch?: typeof fetch;
};

export type FullRequestParams = RequestParams & {
  path: string;
  method: string;
  body?: unknown;
  type?: ContentType;
  format?: "json" | "text" | "blob" | "arrayBuffer" | "formData";
};

export class HttpClient {
  public baseUrl = "";
  private securityData: unknown = null;
  private securityWorker?: ApiConfig["securityWorker"];
  private customFetch: typeof fetch;
  private baseApiParams: RequestParams = {
    credentials: "same-origin",
    headers: {},
  };

  constructor(config: ApiConfig = {}) {
    this.baseUrl = config.baseUrl ?? "";
    this.securityWorker = config.securityWorker;
    this.customFetch = config.customFetch ?? fetch.bind(globalThis);
    this.baseApiParams = { ...this.baseApiParams, ...(config.baseApiParams ?? {}) };
  }

  public setSecurityData(data: unknown): void {
    this.securityData = data;
  }

  private encodeQueryValue(value: Exclude<QueryValue, QueryValue[]>): string {
    if (value instanceof Date) return value.toISOString();
    return String(value);
  }

  private toQueryString(query?: QueryParams): string {
    if (!query) return "";
    const parts: string[] = [];
    for (const [key, value] of Object.entries(query)) {
      if (value === undefined || value === null) continue;
      const values = Array.isArray(value) ? value : [value];
      for (const item of values) {
        if (item === undefined || item === null) continue;
        parts.push(encodeURIComponent(key) + "=" + encodeURIComponent(this.encodeQueryValue(item as Exclude<QueryValue, QueryValue[]>)));
      }
    }
    return parts.length ? "?" + parts.join("&") : "";
  }

  private mergeRequestParams(...params: Array<RequestParams | undefined>): RequestParams {
    const result: RequestParams = {};
    for (const item of params) {
      if (!item) continue;
      Object.assign(result, item);
      result.headers = { ...(result.headers ?? {}), ...(item.headers ?? {}) };
    }
    return result;
  }

  private createFormData(body: unknown): FormData {
    if (body instanceof FormData) return body;
    const formData = new FormData();
    if (!body || typeof body !== "object") return formData;
    for (const [key, value] of Object.entries(body as Record<string, unknown>)) {
      if (value === undefined || value === null) continue;
      const values = Array.isArray(value) ? value : [value];
      for (const item of values) {
        if (item === undefined || item === null) continue;
        if (item instanceof Blob) formData.append(key, item);
        else if (typeof item === "object") formData.append(key, JSON.stringify(item));
        else formData.append(key, String(item));
      }
    }
    return formData;
  }

  private createBody(body: unknown, type?: ContentType): BodyInit | undefined {
    if (body === undefined || body === null) return undefined;
    if (body instanceof Blob || body instanceof FormData || typeof body === "string") return body;
    if (type === ContentType.FormData) return this.createFormData(body);
    if (type === ContentType.UrlEncoded) return this.toQueryString(body as QueryParams).slice(1);
    if (type === ContentType.Text) return String(body);
    return JSON.stringify(body);
  }

  private async parseResponseBody(response: Response, format?: FullRequestParams["format"]): Promise<unknown> {
    if (response.status === 204) return undefined;
    if (format === "blob") return response.blob();
    if (format === "arrayBuffer") return response.arrayBuffer();
    if (format === "formData") return response.formData();
    const text = await response.text();
    if (!text) return undefined;
    const contentType = response.headers.get("content-type") ?? "";
    if (format === "json" || contentType.includes("application/json")) {
      try { return JSON.parse(text); } catch { return text; }
    }
    return text;
  }

  public async request<T = unknown, E = unknown>(requestParams: FullRequestParams): Promise<HttpResponse<T, E>> {
    const secureParams = requestParams.secure && this.securityWorker ? await this.securityWorker(this.securityData) : undefined;
    const params = this.mergeRequestParams(this.baseApiParams, secureParams || {}, requestParams);
    const queryString = this.toQueryString({ ...(requestParams.query ?? {}), ...(params.query ?? {}) });
    const baseUrl = requestParams.baseUrl ?? params.baseUrl ?? this.baseUrl;
    const url = `${baseUrl}${requestParams.path}${queryString}`;
    const headers = new Headers(params.headers as HeadersInit | undefined);

    if (requestParams.body !== undefined && requestParams.type && requestParams.type !== ContentType.FormData && !headers.has("Content-Type")) {
      headers.set("Content-Type", requestParams.type);
    }

    const response = await this.customFetch(url, {
      ...params,
      headers,
      method: requestParams.method,
      body: this.createBody(requestParams.body, requestParams.type),
    });

    const parsed = await this.parseResponseBody(response.clone(), requestParams.format);
    const typedResponse = response as HttpResponse<T, E>;
    if (response.ok) typedResponse.data = parsed as T;
    else typedResponse.error = parsed as E;
    return typedResponse;
  }
}
