import { quoteProperty, refName, safeTypeName } from './names.mjs';

const primitiveMap = {
  integer: 'number',
  number: 'number',
  string: 'string',
  boolean: 'boolean',
  object: 'Record<string, unknown>',
};

function unique(values) {
  return [...new Set(values.filter(Boolean))];
}

function literal(value) {
  return typeof value === 'string' ? JSON.stringify(value) : String(value);
}

export function schemaToType(schema, context = {}) {
  if (!schema) return 'unknown';
  if (schema.$ref) return refName(schema.$ref);

  if (schema.nullable) {
    const copy = { ...schema };
    delete copy.nullable;
    return `${schemaToType(copy, context)} | null`;
  }

  if (schema.const !== undefined) return literal(schema.const);
  if (Array.isArray(schema.enum)) {
    if (schema.enum.length === 0) return 'unknown';
    return schema.enum.map(literal).join(' | ');
  }

  if (Array.isArray(schema.oneOf)) return unique(schema.oneOf.map((item) => schemaToType(item, context))).join(' | ') || 'unknown';
  if (Array.isArray(schema.anyOf)) return unique(schema.anyOf.map((item) => schemaToType(item, context))).join(' | ') || 'unknown';
  if (Array.isArray(schema.allOf)) return unique(schema.allOf.map((item) => schemaToType(item, context))).join(' & ') || 'unknown';

  if (schema.type === 'array') return `${schemaToType(schema.items, context)}[]`;

  if (schema.type === 'object' || schema.properties || schema.additionalProperties) {
    const properties = schema.properties ?? {};
    const required = new Set(schema.required ?? []);
    const entries = Object.entries(properties).map(([name, propertySchema]) => {
      const optional = required.has(name) ? '' : '?';
      const readonly = context.addReadonly ? 'readonly ' : '';
      return `  ${readonly}${quoteProperty(name)}${optional}: ${schemaToType(propertySchema, context)};`;
    });

    if (schema.additionalProperties) {
      const valueType = schema.additionalProperties === true ? 'unknown' : schemaToType(schema.additionalProperties, context);
      entries.push(`  [key: string]: ${valueType};`);
    }

    if (entries.length === 0) return 'Record<string, unknown>';
    return `{
${entries.join('\n')}
}`;
  }

  if (Array.isArray(schema.type)) return unique(schema.type.map((type) => schemaToType({ ...schema, type }, context))).join(' | ');

  if (schema.format === 'binary') return 'File';
  if (schema.format === 'date' || schema.format === 'date-time') return 'string';

  return primitiveMap[schema.type] ?? 'unknown';
}

function schemaComment(schema) {
  const lines = [];
  if (schema.description) lines.push(...String(schema.description).split('\n'));
  if (schema.deprecated) lines.push('@deprecated');
  if (!lines.length) return '';
  return `/**\n${lines.map((line) => ` * ${line}`).join('\n')}\n */\n`;
}

export function generateContracts(document, config) {
  const schemas = document.components?.schemas ?? {};
  const blocks = [
    '/* eslint-disable */',
    '/* tslint:disable */',
    '// This file was generated by typedapi-client-helpers. Do not edit manually.',
  ];

  for (const [rawName, schema] of Object.entries(schemas)) {
    const name = safeTypeName(rawName);
    const comment = schemaComment(schema);

    if (Array.isArray(schema.enum)) {
      if (config.enumNamesAsValues) {
        const members = schema.enum.map((value) => `  ${safeTypeName(String(value))}: ${literal(value)},`).join('\n');
        blocks.push(`${comment}export const ${name} = {\n${members}\n} as const;\nexport type ${name} = (typeof ${name})[keyof typeof ${name}];`);
      } else {
        blocks.push(`${comment}export type ${name} = ${schemaToType(schema, config)};`);
      }
      continue;
    }

    const type = schemaToType(schema, config);
    if (type.startsWith('{\n')) {
      blocks.push(`${comment}export interface ${name} ${type}`);
    } else {
      blocks.push(`${comment}export type ${name} = ${type};`);
    }
  }

  return `${blocks.join('\n\n')}\n`;
}
