/* eslint-disable */
/* tslint:disable */
/*
 * -------------------------------------------------------------------------------------
 * ## THIS FILE WAS GENERATED BY typedapi-client-helpers                              ##
 * ## DO NOT EDIT THIS FILE DIRECTLY                                                  ##
 * ##                                                                                 ##
 * ## AUTHOR: Stef Buurman                                                            ##
 * ## SOURCE: https://github.com/Stef-Buurman/TypedApi/tree/main/npm/typed-api-client ##
 * -------------------------------------------------------------------------------------
 */
import { ContentType, request } from "../generated/http-client";
import type { RequestParams } from "../generated/http-client";
import { typedApiWireSchemas } from "../generated/data-contracts";
import type {
  DeleteNoContentParams,
  EndpointCoverageModel,
  EndpointCoveragePatchRequest,
  EndpointCoverageRequest,
  GetPathAndQueryParams,
  PatchJsonParams,
  PostUrlEncodedPayload,
} from "../generated/data-contracts";
import { fromWireValue, handleApiResponse, toWireValue } from "typedapi-client-helpers";
import type { ApiMethodOptions, ApiResult } from "typedapi-client-helpers";
import { handleGoodResult as typedApiDefaultSuccessHandler, handleErrors as typedApiDefaultErrorHandler } from "../../utils/defaultApiFunctions";

/**
 * No description
 *
 * @tags EndpointCoverage
 * @name GetObject
 * @request GET:/api/endpoint-coverage/object
 */
export async function getObject(
  options: ApiMethodOptions<EndpointCoverageModel, unknown, RequestParams> = {}
): Promise<ApiResult<EndpointCoverageModel, unknown>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<EndpointCoverageModel, unknown>(
    () => request<EndpointCoverageModel, unknown>({
      ...params,
      path: `/api/endpoint-coverage/object`,
      method: "GET",
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      transformResponse: (value) => fromWireValue(value, typedApiWireSchemas["operation:EndpointCoverageGetObjectGETApiEndpointCoverageObject:response"], typedApiWireSchemas) as EndpointCoverageModel,
    },
  );
}

/**
 * No description
 *
 * @tags EndpointCoverage
 * @name GetArray
 * @request GET:/api/endpoint-coverage/array
 */
export async function getArray(
  options: ApiMethodOptions<EndpointCoverageModel[], unknown, RequestParams> = {}
): Promise<ApiResult<EndpointCoverageModel[], unknown>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<EndpointCoverageModel[], unknown>(
    () => request<EndpointCoverageModel[], unknown>({
      ...params,
      path: `/api/endpoint-coverage/array`,
      method: "GET",
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      transformResponse: (value) => fromWireValue(value, typedApiWireSchemas["operation:EndpointCoverageGetArrayGETApiEndpointCoverageArray:response"], typedApiWireSchemas) as EndpointCoverageModel[],
    },
  );
}

/**
 * No description
 *
 * @tags EndpointCoverage
 * @name GetPrimitive
 * @request GET:/api/endpoint-coverage/primitive
 */
export async function getPrimitive(
  options: ApiMethodOptions<number, unknown, RequestParams> = {}
): Promise<ApiResult<number, unknown>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<number, unknown>(
    () => request<number, unknown>({
      ...params,
      path: `/api/endpoint-coverage/primitive`,
      method: "GET",
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      transformResponse: (value) => fromWireValue(value, typedApiWireSchemas["operation:EndpointCoverageGetPrimitiveGETApiEndpointCoveragePrimitive:response"], typedApiWireSchemas) as number,
    },
  );
}

/**
 * No description
 *
 * @tags EndpointCoverage
 * @name GetDictionary
 * @request GET:/api/endpoint-coverage/dictionary
 */
export async function getDictionary(
  options: ApiMethodOptions<Record<string, number>, unknown, RequestParams> = {}
): Promise<ApiResult<Record<string, number>, unknown>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<Record<string, number>, unknown>(
    () => request<Record<string, number>, unknown>({
      ...params,
      path: `/api/endpoint-coverage/dictionary`,
      method: "GET",
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      transformResponse: (value) => fromWireValue(value, typedApiWireSchemas["operation:EndpointCoverageGetDictionaryGETApiEndpointCoverageDictionary:response"], typedApiWireSchemas) as Record<string, number>,
    },
  );
}

/**
 * No description
 *
 * @tags EndpointCoverage
 * @name GetText
 * @request GET:/api/endpoint-coverage/text
 */
export async function getText(
  options: ApiMethodOptions<void, unknown, RequestParams> = {}
): Promise<ApiResult<void, unknown>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<void, unknown>(
    () => request<void, unknown>({
      ...params,
      path: `/api/endpoint-coverage/text`,
      method: "GET",
    }),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler },
  );
}

/**
 * No description
 *
 * @tags EndpointCoverage
 * @name DownloadFile
 * @request GET:/api/endpoint-coverage/download
 */
export async function downloadFile(
  options: ApiMethodOptions<void, unknown, RequestParams> = {}
): Promise<ApiResult<void, unknown>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<void, unknown>(
    () => request<void, unknown>({
      ...params,
      path: `/api/endpoint-coverage/download`,
      method: "GET",
    }),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler },
  );
}

/**
 * No description
 *
 * @tags EndpointCoverage
 * @name GetPathAndQuery
 * @request GET:/api/endpoint-coverage/{id}/details
 */
export async function getPathAndQuery(
  pathParams: GetPathAndQueryParams,
  options: ApiMethodOptions<EndpointCoverageModel, unknown, RequestParams> = {}
): Promise<ApiResult<EndpointCoverageModel, unknown>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<EndpointCoverageModel, unknown>(
    () => request<EndpointCoverageModel, unknown>({
      ...params,
      path: `/api/endpoint-coverage/${encodeURIComponent(String(pathParams["id"]))}/details`,
      method: "GET",
      query: { "includeMetadata": pathParams["includeMetadata"], "culture": pathParams["culture"] },
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      transformResponse: (value) => fromWireValue(value, typedApiWireSchemas["operation:EndpointCoverageGetPathAndQueryGETApiEndpointCoverageIdDetails:response"], typedApiWireSchemas) as EndpointCoverageModel,
    },
  );
}

/**
 * No description
 *
 * @tags EndpointCoverage
 * @name PostJson
 * @request POST:/api/endpoint-coverage/json
 */
export async function postJson(
  data: EndpointCoverageRequest,
  options: ApiMethodOptions<EndpointCoverageModel, unknown, RequestParams> = {}
): Promise<ApiResult<EndpointCoverageModel, unknown>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<EndpointCoverageModel, unknown>(
    () => request<EndpointCoverageModel, unknown>({
      ...params,
      path: `/api/endpoint-coverage/json`,
      method: "POST",
      body: toWireValue(data, typedApiWireSchemas["operation:EndpointCoveragePostJsonPOSTApiEndpointCoverageJson:body"], typedApiWireSchemas),
      type: ContentType.Json,
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      transformResponse: (value) => fromWireValue(value, typedApiWireSchemas["operation:EndpointCoveragePostJsonPOSTApiEndpointCoverageJson:response"], typedApiWireSchemas) as EndpointCoverageModel,
    },
  );
}

/**
 * No description
 *
 * @tags EndpointCoverage
 * @name PostPrimitiveBody
 * @request POST:/api/endpoint-coverage/primitive-body
 */
export async function postPrimitiveBody(
  data: string,
  options: ApiMethodOptions<string, unknown, RequestParams> = {}
): Promise<ApiResult<string, unknown>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<string, unknown>(
    () => request<string, unknown>({
      ...params,
      path: `/api/endpoint-coverage/primitive-body`,
      method: "POST",
      body: toWireValue(data, typedApiWireSchemas["operation:EndpointCoveragePostPrimitiveBodyPOSTApiEndpointCoveragePrimitiveBody:body"], typedApiWireSchemas),
      type: ContentType.Json,
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      transformResponse: (value) => fromWireValue(value, typedApiWireSchemas["operation:EndpointCoveragePostPrimitiveBodyPOSTApiEndpointCoveragePrimitiveBody:response"], typedApiWireSchemas) as string,
    },
  );
}

/**
 * No description
 *
 * @tags EndpointCoverage
 * @name PostUrlEncoded
 * @request POST:/api/endpoint-coverage/url-encoded
 */
export async function postUrlEncoded(
  data: PostUrlEncodedPayload,
  options: ApiMethodOptions<EndpointCoverageModel, unknown, RequestParams> = {}
): Promise<ApiResult<EndpointCoverageModel, unknown>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<EndpointCoverageModel, unknown>(
    () => request<EndpointCoverageModel, unknown>({
      ...params,
      path: `/api/endpoint-coverage/url-encoded`,
      method: "POST",
      body: toWireValue(data, typedApiWireSchemas["operation:EndpointCoveragePostUrlEncodedPOSTApiEndpointCoverageUrlEncoded:body"], typedApiWireSchemas),
      type: ContentType.UrlEncoded,
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      transformResponse: (value) => fromWireValue(value, typedApiWireSchemas["operation:EndpointCoveragePostUrlEncodedPOSTApiEndpointCoverageUrlEncoded:response"], typedApiWireSchemas) as EndpointCoverageModel,
    },
  );
}

/**
 * No description
 *
 * @tags EndpointCoverage
 * @name PostAccepted
 * @request POST:/api/endpoint-coverage/accepted
 */
export async function postAccepted(
  data: EndpointCoverageRequest,
  options: ApiMethodOptions<EndpointCoverageModel, unknown, RequestParams> = {}
): Promise<ApiResult<EndpointCoverageModel, unknown>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<EndpointCoverageModel, unknown>(
    () => request<EndpointCoverageModel, unknown>({
      ...params,
      path: `/api/endpoint-coverage/accepted`,
      method: "POST",
      body: toWireValue(data, typedApiWireSchemas["operation:EndpointCoveragePostAcceptedPOSTApiEndpointCoverageAccepted:body"], typedApiWireSchemas),
      type: ContentType.Json,
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      transformResponse: (value) => fromWireValue(value, typedApiWireSchemas["operation:EndpointCoveragePostAcceptedPOSTApiEndpointCoverageAccepted:response"], typedApiWireSchemas) as EndpointCoverageModel,
    },
  );
}

/**
 * No description
 *
 * @tags EndpointCoverage
 * @name PatchJson
 * @request PATCH:/api/endpoint-coverage/{id}
 */
export async function patchJson(
  pathParams: PatchJsonParams,
  data: EndpointCoveragePatchRequest,
  options: ApiMethodOptions<EndpointCoverageModel, unknown, RequestParams> = {}
): Promise<ApiResult<EndpointCoverageModel, unknown>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<EndpointCoverageModel, unknown>(
    () => request<EndpointCoverageModel, unknown>({
      ...params,
      path: `/api/endpoint-coverage/${encodeURIComponent(String(pathParams["id"]))}`,
      method: "PATCH",
      body: toWireValue(data, typedApiWireSchemas["operation:EndpointCoveragePatchJsonPATCHApiEndpointCoverageId:body"], typedApiWireSchemas),
      type: ContentType.Json,
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      transformResponse: (value) => fromWireValue(value, typedApiWireSchemas["operation:EndpointCoveragePatchJsonPATCHApiEndpointCoverageId:response"], typedApiWireSchemas) as EndpointCoverageModel,
    },
  );
}

/**
 * No description
 *
 * @tags EndpointCoverage
 * @name DeleteNoContent
 * @request DELETE:/api/endpoint-coverage/{id}/no-content
 */
export async function deleteNoContent(
  pathParams: DeleteNoContentParams,
  options: ApiMethodOptions<void, unknown, RequestParams> = {}
): Promise<ApiResult<void, unknown>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<void, unknown>(
    () => request<void, unknown>({
      ...params,
      path: `/api/endpoint-coverage/${encodeURIComponent(String(pathParams["id"]))}/no-content`,
      method: "DELETE",
    }),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler },
  );
}
