/* eslint-disable */
/* tslint:disable */
/*
 * -------------------------------------------------------------------------------------
 * ## THIS FILE WAS GENERATED BY typedapi-client-helpers                              ##
 * ## DO NOT EDIT THIS FILE DIRECTLY                                                  ##
 * ##                                                                                 ##
 * ## AUTHOR: Stef Buurman                                                            ##
 * ## SOURCE: https://github.com/Stef-Buurman/TypedApi/tree/main/npm/typed-api-client ##
 * -------------------------------------------------------------------------------------
 */
import { ContentType, request } from "../generated/http-client";
import type { RequestParams } from "../generated/http-client";
import { typedApiWireSchemas } from "../generated/data-contracts";
import type {
  EndpointCoverageDeleteNoContentParams,
  EndpointCoverageGetPathAndQueryParams,
  EndpointCoverageModel,
  EndpointCoveragePatchJsonParams,
  EndpointCoveragePatchRequest,
  EndpointCoveragePostUrlEncodedPayload,
  EndpointCoverageRequest,
} from "../generated/data-contracts";
import { fromWireValue, handleApiResponse, toWireValue } from "typedapi-client-helpers";
import type { ApiMethodOptions, ApiResult } from "typedapi-client-helpers";
import { handleGoodResult as typedApiDefaultSuccessHandler, handleErrors as typedApiDefaultErrorHandler } from "../../utils/defaultApiFunctions";

/**
 * No description
 *
 * @tags EndpointCoverage
 * @name EndpointCoverageGetObject
 * @request GET:/api/endpoint-coverage/object
 */
export async function endpointCoverageGetObject(
  options: ApiMethodOptions<EndpointCoverageModel, unknown, RequestParams> = {}
): Promise<ApiResult<EndpointCoverageModel, unknown>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<EndpointCoverageModel, unknown>(
    () => request<EndpointCoverageModel, unknown>({
      ...params,
      path: `/api/endpoint-coverage/object`,
      method: "GET",
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      transformResponse: (value) => fromWireValue(value, typedApiWireSchemas["operation:EndpointCoverageGetObjectGETApiEndpointCoverageObject:response"], typedApiWireSchemas) as EndpointCoverageModel,
    },
  );
}

/**
 * No description
 *
 * @tags EndpointCoverage
 * @name EndpointCoverageGetArray
 * @request GET:/api/endpoint-coverage/array
 */
export async function endpointCoverageGetArray(
  options: ApiMethodOptions<EndpointCoverageModel[], unknown, RequestParams> = {}
): Promise<ApiResult<EndpointCoverageModel[], unknown>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<EndpointCoverageModel[], unknown>(
    () => request<EndpointCoverageModel[], unknown>({
      ...params,
      path: `/api/endpoint-coverage/array`,
      method: "GET",
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      transformResponse: (value) => fromWireValue(value, typedApiWireSchemas["operation:EndpointCoverageGetArrayGETApiEndpointCoverageArray:response"], typedApiWireSchemas) as EndpointCoverageModel[],
    },
  );
}

/**
 * No description
 *
 * @tags EndpointCoverage
 * @name EndpointCoverageGetPrimitive
 * @request GET:/api/endpoint-coverage/primitive
 */
export async function endpointCoverageGetPrimitive(
  options: ApiMethodOptions<number, unknown, RequestParams> = {}
): Promise<ApiResult<number, unknown>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<number, unknown>(
    () => request<number, unknown>({
      ...params,
      path: `/api/endpoint-coverage/primitive`,
      method: "GET",
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      transformResponse: (value) => fromWireValue(value, typedApiWireSchemas["operation:EndpointCoverageGetPrimitiveGETApiEndpointCoveragePrimitive:response"], typedApiWireSchemas) as number,
    },
  );
}

/**
 * No description
 *
 * @tags EndpointCoverage
 * @name EndpointCoverageGetDictionary
 * @request GET:/api/endpoint-coverage/dictionary
 */
export async function endpointCoverageGetDictionary(
  options: ApiMethodOptions<Record<string, number>, unknown, RequestParams> = {}
): Promise<ApiResult<Record<string, number>, unknown>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<Record<string, number>, unknown>(
    () => request<Record<string, number>, unknown>({
      ...params,
      path: `/api/endpoint-coverage/dictionary`,
      method: "GET",
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      transformResponse: (value) => fromWireValue(value, typedApiWireSchemas["operation:EndpointCoverageGetDictionaryGETApiEndpointCoverageDictionary:response"], typedApiWireSchemas) as Record<string, number>,
    },
  );
}

/**
 * No description
 *
 * @tags EndpointCoverage
 * @name EndpointCoverageGetText
 * @request GET:/api/endpoint-coverage/text
 */
export async function endpointCoverageGetText(
  options: ApiMethodOptions<void, unknown, RequestParams> = {}
): Promise<ApiResult<void, unknown>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<void, unknown>(
    () => request<void, unknown>({
      ...params,
      path: `/api/endpoint-coverage/text`,
      method: "GET",
    }),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler },
  );
}

/**
 * No description
 *
 * @tags EndpointCoverage
 * @name EndpointCoverageDownloadFile
 * @request GET:/api/endpoint-coverage/download
 */
export async function endpointCoverageDownloadFile(
  options: ApiMethodOptions<void, unknown, RequestParams> = {}
): Promise<ApiResult<void, unknown>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<void, unknown>(
    () => request<void, unknown>({
      ...params,
      path: `/api/endpoint-coverage/download`,
      method: "GET",
    }),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler },
  );
}

/**
 * No description
 *
 * @tags EndpointCoverage
 * @name EndpointCoverageGetPathAndQuery
 * @request GET:/api/endpoint-coverage/{id}/details
 */
export async function endpointCoverageGetPathAndQuery(
  pathParams: EndpointCoverageGetPathAndQueryParams,
  options: ApiMethodOptions<EndpointCoverageModel, unknown, RequestParams> = {}
): Promise<ApiResult<EndpointCoverageModel, unknown>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<EndpointCoverageModel, unknown>(
    () => request<EndpointCoverageModel, unknown>({
      ...params,
      path: `/api/endpoint-coverage/${encodeURIComponent(String(pathParams["id"]))}/details`,
      method: "GET",
      query: { "includeMetadata": pathParams["includeMetadata"], "culture": pathParams["culture"] },
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      transformResponse: (value) => fromWireValue(value, typedApiWireSchemas["operation:EndpointCoverageGetPathAndQueryGETApiEndpointCoverageIdDetails:response"], typedApiWireSchemas) as EndpointCoverageModel,
    },
  );
}

/**
 * No description
 *
 * @tags EndpointCoverage
 * @name EndpointCoveragePostJson
 * @request POST:/api/endpoint-coverage/json
 */
export async function endpointCoveragePostJson(
  data: EndpointCoverageRequest,
  options: ApiMethodOptions<EndpointCoverageModel, unknown, RequestParams> = {}
): Promise<ApiResult<EndpointCoverageModel, unknown>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<EndpointCoverageModel, unknown>(
    () => request<EndpointCoverageModel, unknown>({
      ...params,
      path: `/api/endpoint-coverage/json`,
      method: "POST",
      body: toWireValue(data, typedApiWireSchemas["operation:EndpointCoveragePostJsonPOSTApiEndpointCoverageJson:body"], typedApiWireSchemas),
      type: ContentType.Json,
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      transformResponse: (value) => fromWireValue(value, typedApiWireSchemas["operation:EndpointCoveragePostJsonPOSTApiEndpointCoverageJson:response"], typedApiWireSchemas) as EndpointCoverageModel,
    },
  );
}

/**
 * No description
 *
 * @tags EndpointCoverage
 * @name EndpointCoveragePostPrimitiveBody
 * @request POST:/api/endpoint-coverage/primitive-body
 */
export async function endpointCoveragePostPrimitiveBody(
  data: string,
  options: ApiMethodOptions<string, unknown, RequestParams> = {}
): Promise<ApiResult<string, unknown>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<string, unknown>(
    () => request<string, unknown>({
      ...params,
      path: `/api/endpoint-coverage/primitive-body`,
      method: "POST",
      body: toWireValue(data, typedApiWireSchemas["operation:EndpointCoveragePostPrimitiveBodyPOSTApiEndpointCoveragePrimitiveBody:body"], typedApiWireSchemas),
      type: ContentType.Json,
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      transformResponse: (value) => fromWireValue(value, typedApiWireSchemas["operation:EndpointCoveragePostPrimitiveBodyPOSTApiEndpointCoveragePrimitiveBody:response"], typedApiWireSchemas) as string,
    },
  );
}

/**
 * No description
 *
 * @tags EndpointCoverage
 * @name EndpointCoveragePostUrlEncoded
 * @request POST:/api/endpoint-coverage/url-encoded
 */
export async function endpointCoveragePostUrlEncoded(
  data: EndpointCoveragePostUrlEncodedPayload,
  options: ApiMethodOptions<EndpointCoverageModel, unknown, RequestParams> = {}
): Promise<ApiResult<EndpointCoverageModel, unknown>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<EndpointCoverageModel, unknown>(
    () => request<EndpointCoverageModel, unknown>({
      ...params,
      path: `/api/endpoint-coverage/url-encoded`,
      method: "POST",
      body: toWireValue(data, typedApiWireSchemas["operation:EndpointCoveragePostUrlEncodedPOSTApiEndpointCoverageUrlEncoded:body"], typedApiWireSchemas),
      type: ContentType.UrlEncoded,
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      transformResponse: (value) => fromWireValue(value, typedApiWireSchemas["operation:EndpointCoveragePostUrlEncodedPOSTApiEndpointCoverageUrlEncoded:response"], typedApiWireSchemas) as EndpointCoverageModel,
    },
  );
}

/**
 * No description
 *
 * @tags EndpointCoverage
 * @name EndpointCoveragePostAccepted
 * @request POST:/api/endpoint-coverage/accepted
 */
export async function endpointCoveragePostAccepted(
  data: EndpointCoverageRequest,
  options: ApiMethodOptions<EndpointCoverageModel, unknown, RequestParams> = {}
): Promise<ApiResult<EndpointCoverageModel, unknown>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<EndpointCoverageModel, unknown>(
    () => request<EndpointCoverageModel, unknown>({
      ...params,
      path: `/api/endpoint-coverage/accepted`,
      method: "POST",
      body: toWireValue(data, typedApiWireSchemas["operation:EndpointCoveragePostAcceptedPOSTApiEndpointCoverageAccepted:body"], typedApiWireSchemas),
      type: ContentType.Json,
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      transformResponse: (value) => fromWireValue(value, typedApiWireSchemas["operation:EndpointCoveragePostAcceptedPOSTApiEndpointCoverageAccepted:response"], typedApiWireSchemas) as EndpointCoverageModel,
    },
  );
}

/**
 * No description
 *
 * @tags EndpointCoverage
 * @name EndpointCoveragePatchJson
 * @request PATCH:/api/endpoint-coverage/{id}
 */
export async function endpointCoveragePatchJson(
  pathParams: EndpointCoveragePatchJsonParams,
  data: EndpointCoveragePatchRequest,
  options: ApiMethodOptions<EndpointCoverageModel, unknown, RequestParams> = {}
): Promise<ApiResult<EndpointCoverageModel, unknown>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<EndpointCoverageModel, unknown>(
    () => request<EndpointCoverageModel, unknown>({
      ...params,
      path: `/api/endpoint-coverage/${encodeURIComponent(String(pathParams["id"]))}`,
      method: "PATCH",
      body: toWireValue(data, typedApiWireSchemas["operation:EndpointCoveragePatchJsonPATCHApiEndpointCoverageId:body"], typedApiWireSchemas),
      type: ContentType.Json,
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      transformResponse: (value) => fromWireValue(value, typedApiWireSchemas["operation:EndpointCoveragePatchJsonPATCHApiEndpointCoverageId:response"], typedApiWireSchemas) as EndpointCoverageModel,
    },
  );
}

/**
 * No description
 *
 * @tags EndpointCoverage
 * @name EndpointCoverageDeleteNoContent
 * @request DELETE:/api/endpoint-coverage/{id}/no-content
 */
export async function endpointCoverageDeleteNoContent(
  pathParams: EndpointCoverageDeleteNoContentParams,
  options: ApiMethodOptions<void, unknown, RequestParams> = {}
): Promise<ApiResult<void, unknown>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<void, unknown>(
    () => request<void, unknown>({
      ...params,
      path: `/api/endpoint-coverage/${encodeURIComponent(String(pathParams["id"]))}/no-content`,
      method: "DELETE",
    }),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler },
  );
}
