/* eslint-disable */
/* tslint:disable */
/*
 * --------------------------------------------------------------------------------
 * ## THIS FILE WAS GENERATED BY typedapi-client-helpers                         ##
 * ##                                                                            ##
 * ## AUTHOR: Stef Buurman                                                       ##
 * ## SOURCE: https://github.com/Stef-Buurman/TypedApi/tree/main/npm/typed-api-client ##
 * --------------------------------------------------------------------------------
 */
import { ContentType, request } from "../generated/http-client";
import type { RequestParams } from "../generated/http-client";
import type {
  DeleteNoContentParams,
  EndpointCoverageModel,
  EndpointCoveragePatchRequest,
  EndpointCoverageRequest,
  GetPathAndQueryParams,
  PatchJsonParams,
  PostUrlEncodedPayload,
} from "../generated/data-contracts";
import { handleApiResponse } from "typedapi-client-helpers";
import type { ApiMethodOptions, ApiResult } from "typedapi-client-helpers";
import { handleGoodResult as typedApiDefaultSuccessHandler, handleErrors as typedApiDefaultErrorHandler } from "../../utils/defaultApiFunctions";

/**
 * No description
 *
 * @tags EndpointCoverage
 * @name GetObject
 * @request GET:/api/endpoint-coverage/object
 */
export async function getObject(
  options: ApiMethodOptions<EndpointCoverageModel, any, RequestParams> = {}
): Promise<ApiResult<EndpointCoverageModel>> {
  const { onSuccess, onError, params } = options;
  return handleApiResponse<EndpointCoverageModel, any>(
    () => request<EndpointCoverageModel, any>({
      path: `/api/endpoint-coverage/object`,
      method: "GET",
      format: "json",
      ...params,
    }),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler },
  );
}

/**
 * No description
 *
 * @tags EndpointCoverage
 * @name GetArray
 * @request GET:/api/endpoint-coverage/array
 */
export async function getArray(
  options: ApiMethodOptions<EndpointCoverageModel[], any, RequestParams> = {}
): Promise<ApiResult<EndpointCoverageModel[]>> {
  const { onSuccess, onError, params } = options;
  return handleApiResponse<EndpointCoverageModel[], any>(
    () => request<EndpointCoverageModel[], any>({
      path: `/api/endpoint-coverage/array`,
      method: "GET",
      format: "json",
      ...params,
    }),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler },
  );
}

/**
 * No description
 *
 * @tags EndpointCoverage
 * @name GetPrimitive
 * @request GET:/api/endpoint-coverage/primitive
 */
export async function getPrimitive(
  options: ApiMethodOptions<number, any, RequestParams> = {}
): Promise<ApiResult<number>> {
  const { onSuccess, onError, params } = options;
  return handleApiResponse<number, any>(
    () => request<number, any>({
      path: `/api/endpoint-coverage/primitive`,
      method: "GET",
      format: "json",
      ...params,
    }),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler },
  );
}

/**
 * No description
 *
 * @tags EndpointCoverage
 * @name GetDictionary
 * @request GET:/api/endpoint-coverage/dictionary
 */
export async function getDictionary(
  options: ApiMethodOptions<Record<string, number>, any, RequestParams> = {}
): Promise<ApiResult<Record<string, number>>> {
  const { onSuccess, onError, params } = options;
  return handleApiResponse<Record<string, number>, any>(
    () => request<Record<string, number>, any>({
      path: `/api/endpoint-coverage/dictionary`,
      method: "GET",
      format: "json",
      ...params,
    }),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler },
  );
}

/**
 * No description
 *
 * @tags EndpointCoverage
 * @name GetText
 * @request GET:/api/endpoint-coverage/text
 */
export async function getText(
  options: ApiMethodOptions<void, any, RequestParams> = {}
): Promise<ApiResult<void>> {
  const { onSuccess, onError, params } = options;
  return handleApiResponse<void, any>(
    () => request<void, any>({
      path: `/api/endpoint-coverage/text`,
      method: "GET",
      ...params,
    }),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler },
  );
}

/**
 * No description
 *
 * @tags EndpointCoverage
 * @name DownloadFile
 * @request GET:/api/endpoint-coverage/download
 */
export async function downloadFile(
  options: ApiMethodOptions<void, any, RequestParams> = {}
): Promise<ApiResult<void>> {
  const { onSuccess, onError, params } = options;
  return handleApiResponse<void, any>(
    () => request<void, any>({
      path: `/api/endpoint-coverage/download`,
      method: "GET",
      ...params,
    }),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler },
  );
}

/**
 * No description
 *
 * @tags EndpointCoverage
 * @name GetPathAndQuery
 * @request GET:/api/endpoint-coverage/{id}/details
 */
export async function getPathAndQuery(
  pathParams: GetPathAndQueryParams,
  options: ApiMethodOptions<EndpointCoverageModel, any, RequestParams> = {}
): Promise<ApiResult<EndpointCoverageModel>> {
  const { onSuccess, onError, params } = options;
  return handleApiResponse<EndpointCoverageModel, any>(
    () => request<EndpointCoverageModel, any>({
      path: `/api/endpoint-coverage/${encodeURIComponent(String(pathParams.id))}/details`,
      method: "GET",
      query: { "includeMetadata": pathParams.includeMetadata, "culture": pathParams.culture },
      format: "json",
      ...params,
    }),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler },
  );
}

/**
 * No description
 *
 * @tags EndpointCoverage
 * @name PostJson
 * @request POST:/api/endpoint-coverage/json
 */
export async function postJson(
  data: EndpointCoverageRequest,
  options: ApiMethodOptions<EndpointCoverageModel, any, RequestParams> = {}
): Promise<ApiResult<EndpointCoverageModel>> {
  const { onSuccess, onError, params } = options;
  return handleApiResponse<EndpointCoverageModel, any>(
    () => request<EndpointCoverageModel, any>({
      path: `/api/endpoint-coverage/json`,
      method: "POST",
      body: data,
      type: ContentType.Json,
      format: "json",
      ...params,
    }),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler },
  );
}

/**
 * No description
 *
 * @tags EndpointCoverage
 * @name PostPrimitiveBody
 * @request POST:/api/endpoint-coverage/primitive-body
 */
export async function postPrimitiveBody(
  data: string,
  options: ApiMethodOptions<string, any, RequestParams> = {}
): Promise<ApiResult<string>> {
  const { onSuccess, onError, params } = options;
  return handleApiResponse<string, any>(
    () => request<string, any>({
      path: `/api/endpoint-coverage/primitive-body`,
      method: "POST",
      body: data,
      type: ContentType.Json,
      format: "json",
      ...params,
    }),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler },
  );
}

/**
 * No description
 *
 * @tags EndpointCoverage
 * @name PostUrlEncoded
 * @request POST:/api/endpoint-coverage/url-encoded
 */
export async function postUrlEncoded(
  data: PostUrlEncodedPayload,
  options: ApiMethodOptions<EndpointCoverageModel, any, RequestParams> = {}
): Promise<ApiResult<EndpointCoverageModel>> {
  const { onSuccess, onError, params } = options;
  return handleApiResponse<EndpointCoverageModel, any>(
    () => request<EndpointCoverageModel, any>({
      path: `/api/endpoint-coverage/url-encoded`,
      method: "POST",
      body: data,
      type: ContentType.UrlEncoded,
      format: "json",
      ...params,
    }),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler },
  );
}

/**
 * No description
 *
 * @tags EndpointCoverage
 * @name PostAccepted
 * @request POST:/api/endpoint-coverage/accepted
 */
export async function postAccepted(
  data: EndpointCoverageRequest,
  options: ApiMethodOptions<EndpointCoverageModel, any, RequestParams> = {}
): Promise<ApiResult<EndpointCoverageModel>> {
  const { onSuccess, onError, params } = options;
  return handleApiResponse<EndpointCoverageModel, any>(
    () => request<EndpointCoverageModel, any>({
      path: `/api/endpoint-coverage/accepted`,
      method: "POST",
      body: data,
      type: ContentType.Json,
      format: "json",
      ...params,
    }),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler },
  );
}

/**
 * No description
 *
 * @tags EndpointCoverage
 * @name PatchJson
 * @request PATCH:/api/endpoint-coverage/{id}
 */
export async function patchJson(
  pathParams: PatchJsonParams,
  data: EndpointCoveragePatchRequest,
  options: ApiMethodOptions<EndpointCoverageModel, any, RequestParams> = {}
): Promise<ApiResult<EndpointCoverageModel>> {
  const { onSuccess, onError, params } = options;
  return handleApiResponse<EndpointCoverageModel, any>(
    () => request<EndpointCoverageModel, any>({
      path: `/api/endpoint-coverage/${encodeURIComponent(String(pathParams.id))}`,
      method: "PATCH",
      body: data,
      type: ContentType.Json,
      format: "json",
      ...params,
    }),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler },
  );
}

/**
 * No description
 *
 * @tags EndpointCoverage
 * @name DeleteNoContent
 * @request DELETE:/api/endpoint-coverage/{id}/no-content
 */
export async function deleteNoContent(
  pathParams: DeleteNoContentParams,
  options: ApiMethodOptions<void, any, RequestParams> = {}
): Promise<ApiResult<void>> {
  const { onSuccess, onError, params } = options;
  return handleApiResponse<void, any>(
    () => request<void, any>({
      path: `/api/endpoint-coverage/${encodeURIComponent(String(pathParams.id))}/no-content`,
      method: "DELETE",
      ...params,
    }),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler },
  );
}
