/* eslint-disable */
/* tslint:disable */
/*
 * -------------------------------------------------------------------------------------
 * ## THIS FILE WAS GENERATED BY typedapi-client-helpers                              ##
 * ## DO NOT EDIT THIS FILE DIRECTLY                                                  ##
 * ##                                                                                 ##
 * ## AUTHOR: Stef Buurman                                                            ##
 * ## SOURCE: https://github.com/Stef-Buurman/TypedApi/tree/main/npm/typed-api-client ##
 * -------------------------------------------------------------------------------------
 */
import { request } from "../generated/http-client";
import type { RequestParams } from "../generated/http-client";
import type {
  ApiPaginationSortResponse,
  FilterFormGetHeaderAndQueryParams,
  FilterFormGetMapItemsQueryParams,
  FilterFormGetMixedPathAndQueryParams,
  FilterFormGetPagedQueryParams,
  FilterFormGetUnmarkedParams,
  FilterFormGetWithMethodAttributeQueryParams,
  FilterFormGetWithParameterAttributeQueryParams,
  FilterFormHeaderResponse,
  FilterFormItemModel,
  FilterFormMapQuery,
  FilterFormPathResponse,
  FilterFormQuery,
  HttpValidationProblemDetails,
  ProblemDetails,
} from "../generated/data-contracts";
import {
  buildFilterQuery,
  buildQuery,
  handleApiResponse,
  mergeHeaders,
  toRequestHeaders,
} from "typedapi-client-helpers";
import type {
  ApiMethodOptions,
  ApiResult,
  ExtractDataIfPaginated,
  FilterFormValues,
  SortableKeys,
  SortDirection,
  UnwrapArray,
} from "typedapi-client-helpers";
import { handleGoodResult as typedApiDefaultSuccessHandler, handleErrors as typedApiDefaultErrorHandler, unknownErrorMessage as typedApiDefaultErrorMessage } from "../../utils/defaultApiFunctions";

/**
 * No description
 *
 * @tags FilterForm
 * @name FilterFormGetWithMethodAttribute
 * @request GET:/api/filter-form/method-attribute
 */
export async function filterFormGetWithMethodAttribute(
  filterForm: {
    query?: FilterFormGetWithMethodAttributeQueryParams;
    filters?: FilterFormValues<FilterFormGetWithMethodAttributeQueryParams>[];
  } = {},
  options: ApiMethodOptions<FilterFormQuery | FilterFormMapQuery, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails, RequestParams> = {},
): Promise<ApiResult<FilterFormQuery | FilterFormMapQuery, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>> {
  const { onSuccess, onError, params = {} } = options;
  const builtQuery = {
    ...(filterForm.query ?? {}),
    ...buildFilterQuery<FilterFormGetWithMethodAttributeQueryParams>(filterForm.filters ?? []),
  };

  return handleApiResponse<FilterFormQuery | FilterFormMapQuery, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>(
    () => request<FilterFormQuery | FilterFormMapQuery, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>({
      ...params,
      path: `/api/filter-form/method-attribute`,
      method: "GET",
      query: builtQuery,
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      fallbackErrorMessage: typedApiDefaultErrorMessage,
    },
  );
}

/**
 * No description
 *
 * @tags FilterForm
 * @name FilterFormGetWithParameterAttribute
 * @request GET:/api/filter-form/parameter-attribute
 */
export async function filterFormGetWithParameterAttribute(
  filterForm: {
    query?: FilterFormGetWithParameterAttributeQueryParams;
    filters?: FilterFormValues<FilterFormGetWithParameterAttributeQueryParams>[];
  } = {},
  options: ApiMethodOptions<FilterFormQuery | FilterFormMapQuery, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails, RequestParams> = {},
): Promise<ApiResult<FilterFormQuery | FilterFormMapQuery, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>> {
  const { onSuccess, onError, params = {} } = options;
  const builtQuery = {
    ...(filterForm.query ?? {}),
    ...buildFilterQuery<FilterFormGetWithParameterAttributeQueryParams>(filterForm.filters ?? []),
  };

  return handleApiResponse<FilterFormQuery | FilterFormMapQuery, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>(
    () => request<FilterFormQuery | FilterFormMapQuery, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>({
      ...params,
      path: `/api/filter-form/parameter-attribute`,
      method: "GET",
      query: builtQuery,
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      fallbackErrorMessage: typedApiDefaultErrorMessage,
    },
  );
}

/**
 * No description
 *
 * @tags FilterForm
 * @name FilterFormGetMapItems
 * @request GET:/api/filter-form/map-items
 */
export async function filterFormGetMapItems(
  filterForm: {
    query: FilterFormGetMapItemsQueryParams;
    filters?: FilterFormValues<FilterFormGetMapItemsQueryParams>[];
  },
  options: ApiMethodOptions<FilterFormMapQuery, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails, RequestParams> = {},
): Promise<ApiResult<FilterFormMapQuery, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>> {
  const { onSuccess, onError, params = {} } = options;
  const builtQuery = {
    ...(filterForm.query ?? {}),
    ...buildFilterQuery<FilterFormGetMapItemsQueryParams>(filterForm.filters ?? []),
  };

  return handleApiResponse<FilterFormMapQuery, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>(
    () => request<FilterFormMapQuery, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>({
      ...params,
      path: `/api/filter-form/map-items`,
      method: "GET",
      query: builtQuery,
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      fallbackErrorMessage: typedApiDefaultErrorMessage,
    },
  );
}

/**
 * No description
 *
 * @tags FilterForm
 * @name FilterFormGetUnmarked
 * @request GET:/api/filter-form/unmarked
 */
export async function filterFormGetUnmarked(
  query: FilterFormGetUnmarkedParams = {},
  options: ApiMethodOptions<FilterFormQuery | FilterFormMapQuery, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails, RequestParams> = {}
): Promise<ApiResult<FilterFormQuery | FilterFormMapQuery, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<FilterFormQuery | FilterFormMapQuery, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>(
    () => request<FilterFormQuery | FilterFormMapQuery, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>({
      ...params,
      path: `/api/filter-form/unmarked`,
      method: "GET",
      query: query,
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      fallbackErrorMessage: typedApiDefaultErrorMessage,
    },
  );
}

/**
 * No description
 *
 * @tags FilterForm
 * @name FilterFormGetPaged
 * @request GET:/api/filter-form/paged
 */
export async function filterFormGetPaged(
  filters: FilterFormValues<FilterFormGetPagedQueryParams>[] = [],
  page = 1,
  pageSize = 100,
  sortBy: SortableKeys<ApiPaginationSortResponse<FilterFormItemModel>> | null = null,
  sortDirection?: SortDirection,
  options: ApiMethodOptions<ApiPaginationSortResponse<FilterFormItemModel>, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails, RequestParams> = {},
): Promise<ApiResult<ApiPaginationSortResponse<FilterFormItemModel>, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>> {
  const { onSuccess, onError, params = {} } = options;
  const builtQuery = buildQuery<
    FilterFormGetPagedQueryParams,
    UnwrapArray<ExtractDataIfPaginated<ApiPaginationSortResponse<FilterFormItemModel>>>
  >(filters, page, pageSize, sortBy, sortDirection);

  return handleApiResponse<ApiPaginationSortResponse<FilterFormItemModel>, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>(
    () => request<ApiPaginationSortResponse<FilterFormItemModel>, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>({
      ...params,
      path: `/api/filter-form/paged`,
      method: "GET",
      query: builtQuery,
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      fallbackErrorMessage: typedApiDefaultErrorMessage,
    },
  );
}

/**
 * No description
 *
 * @tags FilterForm
 * @name FilterFormGetMixedPathAndQuery
 * @request GET:/api/filter-form/scope/{scope}
 */
export async function filterFormGetMixedPathAndQuery(
  pathParams: FilterFormGetMixedPathAndQueryParams,
  options: ApiMethodOptions<FilterFormPathResponse, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails, RequestParams> = {}
): Promise<ApiResult<FilterFormPathResponse, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<FilterFormPathResponse, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>(
    () => request<FilterFormPathResponse, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>({
      ...params,
      path: `/api/filter-form/scope/${encodeURIComponent(String(pathParams["scope"]))}`,
      method: "GET",
      query: {
          "Search": pathParams["search"],
          "MinScore": pathParams["minScore"],
          "MaxScore": pathParams["maxScore"],
          "Active": pathParams["active"],
          "CreatedFrom": pathParams["createdFrom"],
          "CreatedTo": pathParams["createdTo"],
          "Categories": pathParams["categories"],
          "ItemIds": pathParams["itemIds"],
          "Echo": pathParams["echo"],
        },
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      fallbackErrorMessage: typedApiDefaultErrorMessage,
    },
  );
}

/**
 * No description
 *
 * @tags FilterForm
 * @name FilterFormGetHeaderAndQuery
 * @request GET:/api/filter-form/header
 */
export async function filterFormGetHeaderAndQuery(
  requestParams: FilterFormGetHeaderAndQueryParams = {},
  options: ApiMethodOptions<FilterFormHeaderResponse, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails, RequestParams> = {}
): Promise<ApiResult<FilterFormHeaderResponse, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<FilterFormHeaderResponse, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>(
    () => request<FilterFormHeaderResponse, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>({
      ...params,
      path: `/api/filter-form/header`,
      method: "GET",
      query: { "search": requestParams["search"] },
      headers: mergeHeaders(params.headers, toRequestHeaders({ "X-Test-Run": requestParams["x-Test-Run"] })),
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      fallbackErrorMessage: typedApiDefaultErrorMessage,
    },
  );
}
