/* eslint-disable */
/* tslint:disable */
/*
 * -------------------------------------------------------------------------------------
 * ## THIS FILE WAS GENERATED BY typedapi-client-helpers                              ##
 * ## DO NOT EDIT THIS FILE DIRECTLY                                                  ##
 * ##                                                                                 ##
 * ## AUTHOR: Stef Buurman                                                            ##
 * ## SOURCE: https://github.com/Stef-Buurman/TypedApi/tree/main/npm/typed-api-client ##
 * -------------------------------------------------------------------------------------
 */
import { ContentType, request } from "../generated/http-client";
import type { RequestParams } from "../generated/http-client";
import type {
  ImportUploadMixedImportPayload,
  ImportUploadProductFilesPayload,
  ImportUploadSupplierFilePayload,
  UploadResult,
} from "../generated/data-contracts";
import { createApiHttpError, handleApiResponse } from "typedapi-client-helpers";
import type { ApiHttpError, ApiMethodOptions, ApiResult } from "typedapi-client-helpers";
import { handleGoodResult as typedApiDefaultSuccessHandler, handleErrors as typedApiDefaultErrorHandler, unknownErrorMessage as typedApiDefaultErrorMessage } from "../../utils/defaultApiFunctions";

/**
 * No description
 *
 * @tags Import
 * @name ImportUploadProductFiles
 * @request POST:/api/imports/products
 */
export async function importUploadProductFiles(
  data: ImportUploadProductFilesPayload,
  options: ApiMethodOptions<UploadResult, ApiHttpError, RequestParams> = {}
): Promise<ApiResult<UploadResult, ApiHttpError>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<UploadResult, ApiHttpError>(
    () => request<UploadResult, ApiHttpError>({
      ...params,
      path: `/api/imports/products`,
      method: "POST",
      body: data,
      type: ContentType.FormData,
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      fallbackErrorMessage: typedApiDefaultErrorMessage,
      transformError: (value, response) => createApiHttpError(response.status, value),
    },
  );
}

/**
 * No description
 *
 * @tags Import
 * @name ImportUploadSupplierFile
 * @request POST:/api/imports/supplier
 */
export async function importUploadSupplierFile(
  data: ImportUploadSupplierFilePayload,
  options: ApiMethodOptions<UploadResult, ApiHttpError, RequestParams> = {}
): Promise<ApiResult<UploadResult, ApiHttpError>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<UploadResult, ApiHttpError>(
    () => request<UploadResult, ApiHttpError>({
      ...params,
      path: `/api/imports/supplier`,
      method: "POST",
      body: data,
      type: ContentType.FormData,
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      fallbackErrorMessage: typedApiDefaultErrorMessage,
      transformError: (value, response) => createApiHttpError(response.status, value),
    },
  );
}

/**
 * No description
 *
 * @tags Import
 * @name ImportUploadMixedImport
 * @request POST:/api/imports/mixed
 */
export async function importUploadMixedImport(
  data: ImportUploadMixedImportPayload,
  options: ApiMethodOptions<UploadResult, ApiHttpError, RequestParams> = {}
): Promise<ApiResult<UploadResult, ApiHttpError>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<UploadResult, ApiHttpError>(
    () => request<UploadResult, ApiHttpError>({
      ...params,
      path: `/api/imports/mixed`,
      method: "POST",
      body: data,
      type: ContentType.FormData,
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      fallbackErrorMessage: typedApiDefaultErrorMessage,
      transformError: (value, response) => createApiHttpError(response.status, value),
    },
  );
}
