/* eslint-disable */
/* tslint:disable */
/*
 * --------------------------------------------------------------------------------
 * ## THIS FILE WAS GENERATED BY typedapi-client-helpers                         ##
 * ##                                                                            ##
 * ## AUTHOR: Stef Buurman                                                       ##
 * ## SOURCE: https://github.com/Stef-Buurman/TypedApi/tree/main/npm/typed-api-client ##
 * --------------------------------------------------------------------------------
 */
import { ContentType, request } from "../generated/http-client";
import type { RequestParams } from "../generated/http-client";
import type {
  UploadMixedImportPayload,
  UploadProductFilesPayload,
  UploadResult,
  UploadSupplierFilePayload,
} from "../generated/data-contracts";
import { handleApiResponse, toFormData } from "typedapi-client-helpers";
import type { ApiMethodOptions, ApiResult } from "typedapi-client-helpers";
import { handleGoodResult as typedApiDefaultSuccessHandler, handleErrors as typedApiDefaultErrorHandler } from "../../utils/defaultApiFunctions";

/**
 * No description
 *
 * @tags Import
 * @name UploadProductFiles
 * @request POST:/api/imports/products
 */
export async function uploadProductFiles(
  data: UploadProductFilesPayload,
  options: ApiMethodOptions<UploadResult, any, RequestParams> = {}
): Promise<ApiResult<UploadResult>> {
  const { onSuccess, onError, params } = options;
  const formData = toFormData(data);

  return handleApiResponse<UploadResult, any>(
    () => request<UploadResult, any>({
      path: `/api/imports/products`,
      method: "POST",
      body: formData,
      type: ContentType.FormData,
      format: "json",
      ...params,
    }),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler },
  );
}

/**
 * No description
 *
 * @tags Import
 * @name UploadSupplierFile
 * @request POST:/api/imports/supplier
 */
export async function uploadSupplierFile(
  data: UploadSupplierFilePayload,
  options: ApiMethodOptions<UploadResult, any, RequestParams> = {}
): Promise<ApiResult<UploadResult>> {
  const { onSuccess, onError, params } = options;
  const formData = toFormData(data);

  return handleApiResponse<UploadResult, any>(
    () => request<UploadResult, any>({
      path: `/api/imports/supplier`,
      method: "POST",
      body: formData,
      type: ContentType.FormData,
      format: "json",
      ...params,
    }),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler },
  );
}

/**
 * No description
 *
 * @tags Import
 * @name UploadMixedImport
 * @request POST:/api/imports/mixed
 */
export async function uploadMixedImport(
  data: UploadMixedImportPayload,
  options: ApiMethodOptions<UploadResult, any, RequestParams> = {}
): Promise<ApiResult<UploadResult>> {
  const { onSuccess, onError, params } = options;
  const formData = toFormData(data);

  return handleApiResponse<UploadResult, any>(
    () => request<UploadResult, any>({
      path: `/api/imports/mixed`,
      method: "POST",
      body: formData,
      type: ContentType.FormData,
      format: "json",
      ...params,
    }),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler },
  );
}
