/* eslint-disable */
/* tslint:disable */
/*
 * -------------------------------------------------------------------------------------
 * ## THIS FILE WAS GENERATED BY typedapi-client-helpers                              ##
 * ## DO NOT EDIT THIS FILE DIRECTLY                                                  ##
 * ##                                                                                 ##
 * ## AUTHOR: Stef Buurman                                                            ##
 * ## SOURCE: https://github.com/Stef-Buurman/TypedApi/tree/main/npm/typed-api-client ##
 * -------------------------------------------------------------------------------------
 */
import { ContentType, request } from "../generated/http-client";
import type { RequestParams } from "../generated/http-client";
import type { ProjectModel, TeamMemberModel } from "../generated/data-contracts";
import { createApiHttpError, handleApiResponse } from "typedapi-client-helpers";
import type { ApiHttpError, ApiMethodOptions, ApiResult } from "typedapi-client-helpers";
import { handleGoodResult as typedApiDefaultSuccessHandler, handleErrors as typedApiDefaultErrorHandler, unknownErrorMessage as typedApiDefaultErrorMessage } from "../../utils/defaultApiFunctions";

/**
 * No description
 *
 * @tags Inheritance
 * @name InheritanceGetTeamMember
 * @request GET:/api/inheritance/team-member
 */
export async function inheritanceGetTeamMember(
  options: ApiMethodOptions<TeamMemberModel, ApiHttpError, RequestParams> = {}
): Promise<ApiResult<TeamMemberModel, ApiHttpError>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<TeamMemberModel, ApiHttpError>(
    () => request<TeamMemberModel, ApiHttpError>({
      ...params,
      path: `/api/inheritance/team-member`,
      method: "GET",
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      fallbackErrorMessage: typedApiDefaultErrorMessage,
      transformError: (value, response) => createApiHttpError(response.status, value),
    },
  );
}

/**
 * No description
 *
 * @tags Inheritance
 * @name InheritanceGetProject
 * @request GET:/api/inheritance/project
 */
export async function inheritanceGetProject(
  options: ApiMethodOptions<ProjectModel, ApiHttpError, RequestParams> = {}
): Promise<ApiResult<ProjectModel, ApiHttpError>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<ProjectModel, ApiHttpError>(
    () => request<ProjectModel, ApiHttpError>({
      ...params,
      path: `/api/inheritance/project`,
      method: "GET",
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      fallbackErrorMessage: typedApiDefaultErrorMessage,
      transformError: (value, response) => createApiHttpError(response.status, value),
    },
  );
}

/**
 * No description
 *
 * @tags Inheritance
 * @name InheritanceEchoProject
 * @request POST:/api/inheritance/project
 */
export async function inheritanceEchoProject(
  data: ProjectModel,
  options: ApiMethodOptions<ProjectModel, ApiHttpError, RequestParams> = {}
): Promise<ApiResult<ProjectModel, ApiHttpError>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<ProjectModel, ApiHttpError>(
    () => request<ProjectModel, ApiHttpError>({
      ...params,
      path: `/api/inheritance/project`,
      method: "POST",
      body: data,
      type: ContentType.Json,
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      fallbackErrorMessage: typedApiDefaultErrorMessage,
      transformError: (value, response) => createApiHttpError(response.status, value),
    },
  );
}
