/* eslint-disable */
/* tslint:disable */
/*
 * --------------------------------------------------------------------------------
 * ## THIS FILE WAS GENERATED BY typedapi-client-helpers                         ##
 * ##                                                                            ##
 * ## AUTHOR: Stef Buurman                                                       ##
 * ## SOURCE: https://github.com/Stef-Buurman/TypedApi/tree/main/npm/typed-api-client ##
 * --------------------------------------------------------------------------------
 */
import { ContentType, request } from "../generated/http-client";
import type { RequestParams } from "../generated/http-client";
import type {
  ApproveOrderParams,
  CancelOrderParams,
  DeleteOrderParams,
  GetOrderByIdParams,
  GetOrdersParams,
  OrderModel,
  OrderModelApiPaginationResponse,
  OrderRequest,
  UpdateOrderParams,
} from "../generated/data-contracts";
import { buildQuery, handleApiResponse } from "typedapi-client-helpers";
import type {
  ApiMethodOptions,
  ApiResult,
  ExtractDataIfPaginated,
  FilterFormValues,
  SortableKeys,
  SortDirection,
  UnwrapArray,
} from "typedapi-client-helpers";
import { handleGoodResult as typedApiDefaultSuccessHandler, handleErrors as typedApiDefaultErrorHandler } from "../../utils/defaultApiFunctions";

export type GetOrdersQuery = NonNullable<GetOrdersParams>;

/**
 * No description
 *
 * @tags Order
 * @name GetOrders
 * @request GET:/api/orders
 */
export async function getOrders(
  filters: FilterFormValues<GetOrdersQuery>[] = [],
  page = 1,
  pageSize = 100,
  sortBy: SortableKeys<OrderModelApiPaginationResponse> | null = null,
  sortDirection?: SortDirection,
  options: ApiMethodOptions<OrderModelApiPaginationResponse, any, RequestParams> = {},
): Promise<ApiResult<OrderModelApiPaginationResponse>> {
  const { onSuccess, onError, params } = options;
  const builtQuery = buildQuery<
    GetOrdersQuery,
    UnwrapArray<ExtractDataIfPaginated<OrderModelApiPaginationResponse>>
  >(filters, page, pageSize, sortBy, sortDirection);

  return handleApiResponse<OrderModelApiPaginationResponse, any>(
    () => request<OrderModelApiPaginationResponse, any>({
      path: `/api/orders`,
      method: "GET",
      query: builtQuery ?? {},
      format: "json",
      ...params,
    }),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler },
  );
}

/**
 * No description
 *
 * @tags Order
 * @name CreateOrder
 * @request POST:/api/orders
 */
export async function createOrder(
  data: OrderRequest,
  options: ApiMethodOptions<OrderModel, any, RequestParams> = {}
): Promise<ApiResult<OrderModel>> {
  const { onSuccess, onError, params } = options;
  return handleApiResponse<OrderModel, any>(
    () => request<OrderModel, any>({
      path: `/api/orders`,
      method: "POST",
      body: data,
      type: ContentType.Json,
      format: "json",
      ...params,
    }),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler },
  );
}

/**
 * No description
 *
 * @tags Order
 * @name GetOrderById
 * @request GET:/api/orders/{id}
 */
export async function getOrderById(
  pathParams: GetOrderByIdParams,
  options: ApiMethodOptions<OrderModel, any, RequestParams> = {}
): Promise<ApiResult<OrderModel>> {
  const { onSuccess, onError, params } = options;
  return handleApiResponse<OrderModel, any>(
    () => request<OrderModel, any>({
      path: `/api/orders/${encodeURIComponent(String(pathParams.id))}`,
      method: "GET",
      format: "json",
      ...params,
    }),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler },
  );
}

/**
 * No description
 *
 * @tags Order
 * @name UpdateOrder
 * @request PUT:/api/orders/{id}
 */
export async function updateOrder(
  pathParams: UpdateOrderParams,
  data: OrderRequest,
  options: ApiMethodOptions<OrderModel, any, RequestParams> = {}
): Promise<ApiResult<OrderModel>> {
  const { onSuccess, onError, params } = options;
  return handleApiResponse<OrderModel, any>(
    () => request<OrderModel, any>({
      path: `/api/orders/${encodeURIComponent(String(pathParams.id))}`,
      method: "PUT",
      body: data,
      type: ContentType.Json,
      format: "json",
      ...params,
    }),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler },
  );
}

/**
 * No description
 *
 * @tags Order
 * @name DeleteOrder
 * @request DELETE:/api/orders/{id}
 */
export async function deleteOrder(
  pathParams: DeleteOrderParams,
  options: ApiMethodOptions<void, any, RequestParams> = {}
): Promise<ApiResult<void>> {
  const { onSuccess, onError, params } = options;
  return handleApiResponse<void, any>(
    () => request<void, any>({
      path: `/api/orders/${encodeURIComponent(String(pathParams.id))}`,
      method: "DELETE",
      ...params,
    }),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler },
  );
}

/**
 * No description
 *
 * @tags Order
 * @name ApproveOrder
 * @request POST:/api/orders/{id}/approve
 */
export async function approveOrder(
  pathParams: ApproveOrderParams,
  options: ApiMethodOptions<OrderModel, any, RequestParams> = {}
): Promise<ApiResult<OrderModel>> {
  const { onSuccess, onError, params } = options;
  return handleApiResponse<OrderModel, any>(
    () => request<OrderModel, any>({
      path: `/api/orders/${encodeURIComponent(String(pathParams.id))}/approve`,
      method: "POST",
      format: "json",
      ...params,
    }),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler },
  );
}

/**
 * No description
 *
 * @tags Order
 * @name CancelOrder
 * @request POST:/api/orders/{id}/cancel
 */
export async function cancelOrder(
  pathParams: CancelOrderParams,
  options: ApiMethodOptions<OrderModel, any, RequestParams> = {}
): Promise<ApiResult<OrderModel>> {
  const { onSuccess, onError, params } = options;
  return handleApiResponse<OrderModel, any>(
    () => request<OrderModel, any>({
      path: `/api/orders/${encodeURIComponent(String(pathParams.id))}/cancel`,
      method: "POST",
      query: { "reason": pathParams.reason },
      format: "json",
      ...params,
    }),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler },
  );
}
