/* eslint-disable */
/* tslint:disable */
/*
 * -------------------------------------------------------------------------------------
 * ## THIS FILE WAS GENERATED BY typedapi-client-helpers                              ##
 * ## DO NOT EDIT THIS FILE DIRECTLY                                                  ##
 * ##                                                                                 ##
 * ## AUTHOR: Stef Buurman                                                            ##
 * ## SOURCE: https://github.com/Stef-Buurman/TypedApi/tree/main/npm/typed-api-client ##
 * -------------------------------------------------------------------------------------
 */
import { ContentType, request } from "../generated/http-client";
import type { RequestParams } from "../generated/http-client";
import { typedApiWireSchemas } from "../generated/data-contracts";
import type {
  ApproveOrderParams,
  CancelOrderParams,
  DeleteOrderParams,
  GetOrderByIdParams,
  GetOrdersQueryParams,
  OrderModel,
  OrderModelApiPaginationSortResponse,
  OrderRequest,
  UpdateOrderParams,
} from "../generated/data-contracts";
import {
  buildQuery,
  fromWireValue,
  handleApiResponse,
  toWireValue,
} from "typedapi-client-helpers";
import type {
  ApiMethodOptions,
  ApiResult,
  ExtractDataIfPaginated,
  FilterFormValues,
  SortableKeys,
  SortDirection,
  UnwrapArray,
} from "typedapi-client-helpers";
import { handleGoodResult as typedApiDefaultSuccessHandler, handleErrors as typedApiDefaultErrorHandler } from "../../utils/defaultApiFunctions";

/**
 * No description
 *
 * @tags Order
 * @name GetOrders
 * @request GET:/api/orders
 */
export async function getOrders(
  filters: FilterFormValues<GetOrdersQueryParams>[] = [],
  page = 1,
  pageSize = 100,
  sortBy: SortableKeys<OrderModelApiPaginationSortResponse> | null = null,
  sortDirection?: SortDirection,
  options: ApiMethodOptions<OrderModelApiPaginationSortResponse, unknown, RequestParams> = {},
): Promise<ApiResult<OrderModelApiPaginationSortResponse, unknown>> {
  const { onSuccess, onError, params = {} } = options;
  const builtQuery = buildQuery<
    GetOrdersQueryParams,
    UnwrapArray<ExtractDataIfPaginated<OrderModelApiPaginationSortResponse>>
  >(filters, page, pageSize, sortBy, sortDirection);

  return handleApiResponse<OrderModelApiPaginationSortResponse, unknown>(
    () => request<OrderModelApiPaginationSortResponse, unknown>({
      ...params,
      path: `/api/orders`,
      method: "GET",
      query: builtQuery,
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      transformResponse: (value) => fromWireValue(value, typedApiWireSchemas["operation:OrderGetOrdersGETApiOrders:response"], typedApiWireSchemas) as OrderModelApiPaginationSortResponse,
    },
  );
}

/**
 * No description
 *
 * @tags Order
 * @name CreateOrder
 * @request POST:/api/orders
 */
export async function createOrder(
  data: OrderRequest,
  options: ApiMethodOptions<OrderModel, unknown, RequestParams> = {}
): Promise<ApiResult<OrderModel, unknown>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<OrderModel, unknown>(
    () => request<OrderModel, unknown>({
      ...params,
      path: `/api/orders`,
      method: "POST",
      body: toWireValue(data, typedApiWireSchemas["operation:OrderCreateOrderPOSTApiOrders:body"], typedApiWireSchemas),
      type: ContentType.Json,
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      transformResponse: (value) => fromWireValue(value, typedApiWireSchemas["operation:OrderCreateOrderPOSTApiOrders:response"], typedApiWireSchemas) as OrderModel,
    },
  );
}

/**
 * No description
 *
 * @tags Order
 * @name GetOrderById
 * @request GET:/api/orders/{id}
 */
export async function getOrderById(
  pathParams: GetOrderByIdParams,
  options: ApiMethodOptions<OrderModel, unknown, RequestParams> = {}
): Promise<ApiResult<OrderModel, unknown>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<OrderModel, unknown>(
    () => request<OrderModel, unknown>({
      ...params,
      path: `/api/orders/${encodeURIComponent(String(pathParams["id"]))}`,
      method: "GET",
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      transformResponse: (value) => fromWireValue(value, typedApiWireSchemas["operation:OrderGetOrderByIdGETApiOrdersId:response"], typedApiWireSchemas) as OrderModel,
    },
  );
}

/**
 * No description
 *
 * @tags Order
 * @name UpdateOrder
 * @request PUT:/api/orders/{id}
 */
export async function updateOrder(
  pathParams: UpdateOrderParams,
  data: OrderRequest,
  options: ApiMethodOptions<OrderModel, unknown, RequestParams> = {}
): Promise<ApiResult<OrderModel, unknown>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<OrderModel, unknown>(
    () => request<OrderModel, unknown>({
      ...params,
      path: `/api/orders/${encodeURIComponent(String(pathParams["id"]))}`,
      method: "PUT",
      body: toWireValue(data, typedApiWireSchemas["operation:OrderUpdateOrderPUTApiOrdersId:body"], typedApiWireSchemas),
      type: ContentType.Json,
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      transformResponse: (value) => fromWireValue(value, typedApiWireSchemas["operation:OrderUpdateOrderPUTApiOrdersId:response"], typedApiWireSchemas) as OrderModel,
    },
  );
}

/**
 * No description
 *
 * @tags Order
 * @name DeleteOrder
 * @request DELETE:/api/orders/{id}
 */
export async function deleteOrder(
  pathParams: DeleteOrderParams,
  options: ApiMethodOptions<void, unknown, RequestParams> = {}
): Promise<ApiResult<void, unknown>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<void, unknown>(
    () => request<void, unknown>({
      ...params,
      path: `/api/orders/${encodeURIComponent(String(pathParams["id"]))}`,
      method: "DELETE",
    }),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler },
  );
}

/**
 * No description
 *
 * @tags Order
 * @name ApproveOrder
 * @request POST:/api/orders/{id}/approve
 */
export async function approveOrder(
  pathParams: ApproveOrderParams,
  options: ApiMethodOptions<OrderModel, unknown, RequestParams> = {}
): Promise<ApiResult<OrderModel, unknown>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<OrderModel, unknown>(
    () => request<OrderModel, unknown>({
      ...params,
      path: `/api/orders/${encodeURIComponent(String(pathParams["id"]))}/approve`,
      method: "POST",
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      transformResponse: (value) => fromWireValue(value, typedApiWireSchemas["operation:OrderApproveOrderPOSTApiOrdersIdApprove:response"], typedApiWireSchemas) as OrderModel,
    },
  );
}

/**
 * No description
 *
 * @tags Order
 * @name CancelOrder
 * @request POST:/api/orders/{id}/cancel
 */
export async function cancelOrder(
  pathParams: CancelOrderParams,
  options: ApiMethodOptions<OrderModel, unknown, RequestParams> = {}
): Promise<ApiResult<OrderModel, unknown>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<OrderModel, unknown>(
    () => request<OrderModel, unknown>({
      ...params,
      path: `/api/orders/${encodeURIComponent(String(pathParams["id"]))}/cancel`,
      method: "POST",
      query: { "reason": pathParams["reason"] },
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      transformResponse: (value) => fromWireValue(value, typedApiWireSchemas["operation:OrderCancelOrderPOSTApiOrdersIdCancel:response"], typedApiWireSchemas) as OrderModel,
    },
  );
}
