/* eslint-disable */
/* tslint:disable */
/*
 * --------------------------------------------------------------------------------
 * ## THIS FILE WAS GENERATED BY typedapi-client-helpers                         ##
 * ##                                                                            ##
 * ## AUTHOR: Stef Buurman                                                       ##
 * ## SOURCE: https://github.com/Stef-Buurman/TypedApi/tree/main/npm/typed-api-client ##
 * --------------------------------------------------------------------------------
 */
import { ContentType, request } from "../generated/http-client";
import type { RequestParams } from "../generated/http-client";
import type {
  DeleteProductParams,
  ExportProductsParams,
  GetProductByIdParams,
  GetProductsParams,
  ProductModel,
  ProductRequest,
  ProductTableRowApiPaginationResponse,
  ToggleProductActiveParams,
  UpdateProductParams,
} from "../generated/data-contracts";
import { buildQuery, handleApiResponse } from "typedapi-client-helpers";
import type {
  ApiMethodOptions,
  ApiResult,
  ExtractDataIfPaginated,
  FilterFormValues,
  SortableKeys,
  SortDirection,
  UnwrapArray,
} from "typedapi-client-helpers";
import { handleGoodResult as typedApiDefaultSuccessHandler, handleErrors as typedApiDefaultErrorHandler } from "../../utils/defaultApiFunctions";

export type GetProductsQuery = NonNullable<GetProductsParams>;
export type ExportProductsQuery = NonNullable<ExportProductsParams>;

/**
 * No description
 *
 * @tags Product
 * @name GetProducts
 * @request GET:/api/products
 */
export async function getProducts(
  filters: FilterFormValues<GetProductsQuery>[] = [],
  page = 1,
  pageSize = 100,
  sortBy: SortableKeys<ProductTableRowApiPaginationResponse> | null = null,
  sortDirection?: SortDirection,
  options: ApiMethodOptions<ProductTableRowApiPaginationResponse, any, RequestParams> = {},
): Promise<ApiResult<ProductTableRowApiPaginationResponse>> {
  const { onSuccess, onError, params } = options;
  const builtQuery = buildQuery<
    GetProductsQuery,
    UnwrapArray<ExtractDataIfPaginated<ProductTableRowApiPaginationResponse>>
  >(filters, page, pageSize, sortBy, sortDirection);

  return handleApiResponse<ProductTableRowApiPaginationResponse, any>(
    () => request<ProductTableRowApiPaginationResponse, any>({
      path: `/api/products`,
      method: "GET",
      query: builtQuery ?? {},
      format: "json",
      ...params,
    }),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler },
  );
}

/**
 * No description
 *
 * @tags Product
 * @name CreateProduct
 * @request POST:/api/products
 */
export async function createProduct(
  data: ProductRequest,
  options: ApiMethodOptions<ProductModel, any, RequestParams> = {}
): Promise<ApiResult<ProductModel>> {
  const { onSuccess, onError, params } = options;
  return handleApiResponse<ProductModel, any>(
    () => request<ProductModel, any>({
      path: `/api/products`,
      method: "POST",
      body: data,
      type: ContentType.Json,
      format: "json",
      ...params,
    }),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler },
  );
}

/**
 * No description
 *
 * @tags Product
 * @name GetProductById
 * @request GET:/api/products/{id}
 */
export async function getProductById(
  pathParams: GetProductByIdParams,
  options: ApiMethodOptions<ProductModel, any, RequestParams> = {}
): Promise<ApiResult<ProductModel>> {
  const { onSuccess, onError, params } = options;
  return handleApiResponse<ProductModel, any>(
    () => request<ProductModel, any>({
      path: `/api/products/${encodeURIComponent(String(pathParams.id))}`,
      method: "GET",
      format: "json",
      ...params,
    }),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler },
  );
}

/**
 * No description
 *
 * @tags Product
 * @name UpdateProduct
 * @request PUT:/api/products/{id}
 */
export async function updateProduct(
  pathParams: UpdateProductParams,
  data: ProductRequest,
  options: ApiMethodOptions<ProductModel, any, RequestParams> = {}
): Promise<ApiResult<ProductModel>> {
  const { onSuccess, onError, params } = options;
  return handleApiResponse<ProductModel, any>(
    () => request<ProductModel, any>({
      path: `/api/products/${encodeURIComponent(String(pathParams.id))}`,
      method: "PUT",
      body: data,
      type: ContentType.Json,
      format: "json",
      ...params,
    }),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler },
  );
}

/**
 * No description
 *
 * @tags Product
 * @name DeleteProduct
 * @request DELETE:/api/products/{id}
 */
export async function deleteProduct(
  pathParams: DeleteProductParams,
  options: ApiMethodOptions<void, any, RequestParams> = {}
): Promise<ApiResult<void>> {
  const { onSuccess, onError, params } = options;
  return handleApiResponse<void, any>(
    () => request<void, any>({
      path: `/api/products/${encodeURIComponent(String(pathParams.id))}`,
      method: "DELETE",
      ...params,
    }),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler },
  );
}

/**
 * No description
 *
 * @tags Product
 * @name ToggleProductActive
 * @request POST:/api/products/{id}/toggle-active
 */
export async function toggleProductActive(
  pathParams: ToggleProductActiveParams,
  options: ApiMethodOptions<ProductModel, any, RequestParams> = {}
): Promise<ApiResult<ProductModel>> {
  const { onSuccess, onError, params } = options;
  return handleApiResponse<ProductModel, any>(
    () => request<ProductModel, any>({
      path: `/api/products/${encodeURIComponent(String(pathParams.id))}/toggle-active`,
      method: "POST",
      format: "json",
      ...params,
    }),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler },
  );
}

/**
 * No description
 *
 * @tags Product
 * @name ExportProducts
 * @request GET:/api/products/export
 */
export async function exportProducts(
  query?: ExportProductsQuery,
  options: ApiMethodOptions<void, any, RequestParams> = {},
): Promise<ApiResult<void>> {
  const { onSuccess, onError, params } = options;

  return handleApiResponse<void, any>(
    () => request<void, any>({
      path: `/api/products/export`,
      method: "GET",
      query: query ?? {},
      ...params,
    }),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler },
  );
}
