/* eslint-disable */
/* tslint:disable */
/*
 * -------------------------------------------------------------------------------------
 * ## THIS FILE WAS GENERATED BY typedapi-client-helpers                              ##
 * ## DO NOT EDIT THIS FILE DIRECTLY                                                  ##
 * ##                                                                                 ##
 * ## AUTHOR: Stef Buurman                                                            ##
 * ## SOURCE: https://github.com/Stef-Buurman/TypedApi/tree/main/npm/typed-api-client ##
 * -------------------------------------------------------------------------------------
 */
import { ContentType, request } from "../generated/http-client";
import type { RequestParams } from "../generated/http-client";
import { typedApiWireSchemas } from "../generated/data-contracts";
import type {
  ApiSortResponse,
  ProductDeleteProductParams,
  ProductExportProductsParams,
  ProductGetProductByIdParams,
  ProductGetProductSortStateParams,
  ProductGetProductsQueryParams,
  ProductModel,
  ProductRequest,
  ProductTableRowApiPaginationSortResponse,
  ProductToggleProductActiveParams,
  ProductUpdateProductParams,
} from "../generated/data-contracts";
import {
  buildQuery,
  createApiHttpError,
  fromWireValue,
  handleApiResponse,
  toWireValue,
} from "typedapi-client-helpers";
import type {
  ApiHttpError,
  ApiMethodOptions,
  ApiResult,
  ExtractDataIfPaginated,
  FilterFormValues,
  SortableKeys,
  SortDirection,
  UnwrapArray,
} from "typedapi-client-helpers";
import { handleGoodResult as typedApiDefaultSuccessHandler, handleErrors as typedApiDefaultErrorHandler } from "../../utils/defaultApiFunctions";

/**
 * No description
 *
 * @tags Product
 * @name ProductGetProducts
 * @request GET:/api/products
 */
export async function productGetProducts(
  filters: FilterFormValues<ProductGetProductsQueryParams>[] = [],
  page = 1,
  pageSize = 100,
  sortBy: SortableKeys<ProductTableRowApiPaginationSortResponse> | null = null,
  sortDirection?: SortDirection,
  options: ApiMethodOptions<ProductTableRowApiPaginationSortResponse, ApiHttpError, RequestParams> = {},
): Promise<ApiResult<ProductTableRowApiPaginationSortResponse, ApiHttpError>> {
  const { onSuccess, onError, params = {} } = options;
  const builtQuery = buildQuery<
    ProductGetProductsQueryParams,
    UnwrapArray<ExtractDataIfPaginated<ProductTableRowApiPaginationSortResponse>>
  >(filters, page, pageSize, sortBy, sortDirection);

  return handleApiResponse<ProductTableRowApiPaginationSortResponse, ApiHttpError>(
    () => request<ProductTableRowApiPaginationSortResponse, ApiHttpError>({
      ...params,
      path: `/api/products`,
      method: "GET",
      query: builtQuery,
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      transformResponse: (value) => fromWireValue(value, typedApiWireSchemas["operation:ProductGetProductsGETApiProducts:response"], typedApiWireSchemas) as ProductTableRowApiPaginationSortResponse,
      transformError: (value, response) => createApiHttpError(response.status, value),
    },
  );
}

/**
 * No description
 *
 * @tags Product
 * @name ProductCreateProduct
 * @request POST:/api/products
 */
export async function productCreateProduct(
  data: ProductRequest,
  options: ApiMethodOptions<ProductModel, ApiHttpError, RequestParams> = {}
): Promise<ApiResult<ProductModel, ApiHttpError>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<ProductModel, ApiHttpError>(
    () => request<ProductModel, ApiHttpError>({
      ...params,
      path: `/api/products`,
      method: "POST",
      body: toWireValue(data, typedApiWireSchemas["operation:ProductCreateProductPOSTApiProducts:body"], typedApiWireSchemas),
      type: ContentType.Json,
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      transformResponse: (value) => fromWireValue(value, typedApiWireSchemas["operation:ProductCreateProductPOSTApiProducts:response"], typedApiWireSchemas) as ProductModel,
      transformError: (value, response) => createApiHttpError(response.status, value),
    },
  );
}

/**
 * No description
 *
 * @tags Product
 * @name ProductGetProductSortState
 * @request GET:/api/products/sort-state
 */
export async function productGetProductSortState(
  query: ProductGetProductSortStateParams = {},
  options: ApiMethodOptions<ApiSortResponse, ApiHttpError, RequestParams> = {}
): Promise<ApiResult<ApiSortResponse, ApiHttpError>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<ApiSortResponse, ApiHttpError>(
    () => request<ApiSortResponse, ApiHttpError>({
      ...params,
      path: `/api/products/sort-state`,
      method: "GET",
      query: { "sortBy": query["sortBy"], "sortDirection": query["sortDirection"] },
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      transformResponse: (value) => fromWireValue(value, typedApiWireSchemas["operation:ProductGetProductSortStateGETApiProductsSortState:response"], typedApiWireSchemas) as ApiSortResponse,
      transformError: (value, response) => createApiHttpError(response.status, value),
    },
  );
}

/**
 * No description
 *
 * @tags Product
 * @name ProductGetProductById
 * @request GET:/api/products/{id}
 */
export async function productGetProductById(
  pathParams: ProductGetProductByIdParams,
  options: ApiMethodOptions<ProductModel, ApiHttpError, RequestParams> = {}
): Promise<ApiResult<ProductModel, ApiHttpError>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<ProductModel, ApiHttpError>(
    () => request<ProductModel, ApiHttpError>({
      ...params,
      path: `/api/products/${encodeURIComponent(String(pathParams["id"]))}`,
      method: "GET",
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      transformResponse: (value) => fromWireValue(value, typedApiWireSchemas["operation:ProductGetProductByIdGETApiProductsId:response"], typedApiWireSchemas) as ProductModel,
      transformError: (value, response) => createApiHttpError(response.status, value),
    },
  );
}

/**
 * No description
 *
 * @tags Product
 * @name ProductUpdateProduct
 * @request PUT:/api/products/{id}
 */
export async function productUpdateProduct(
  pathParams: ProductUpdateProductParams,
  data: ProductRequest,
  options: ApiMethodOptions<ProductModel, ApiHttpError, RequestParams> = {}
): Promise<ApiResult<ProductModel, ApiHttpError>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<ProductModel, ApiHttpError>(
    () => request<ProductModel, ApiHttpError>({
      ...params,
      path: `/api/products/${encodeURIComponent(String(pathParams["id"]))}`,
      method: "PUT",
      body: toWireValue(data, typedApiWireSchemas["operation:ProductUpdateProductPUTApiProductsId:body"], typedApiWireSchemas),
      type: ContentType.Json,
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      transformResponse: (value) => fromWireValue(value, typedApiWireSchemas["operation:ProductUpdateProductPUTApiProductsId:response"], typedApiWireSchemas) as ProductModel,
      transformError: (value, response) => createApiHttpError(response.status, value),
    },
  );
}

/**
 * No description
 *
 * @tags Product
 * @name ProductDeleteProduct
 * @request DELETE:/api/products/{id}
 */
export async function productDeleteProduct(
  pathParams: ProductDeleteProductParams,
  options: ApiMethodOptions<void, ApiHttpError, RequestParams> = {}
): Promise<ApiResult<void, ApiHttpError>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<void, ApiHttpError>(
    () => request<void, ApiHttpError>({
      ...params,
      path: `/api/products/${encodeURIComponent(String(pathParams["id"]))}`,
      method: "DELETE",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      transformError: (value, response) => createApiHttpError(response.status, value),
    },
  );
}

/**
 * No description
 *
 * @tags Product
 * @name ProductToggleProductActive
 * @request POST:/api/products/{id}/toggle-active
 */
export async function productToggleProductActive(
  pathParams: ProductToggleProductActiveParams,
  options: ApiMethodOptions<ProductModel, ApiHttpError, RequestParams> = {}
): Promise<ApiResult<ProductModel, ApiHttpError>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<ProductModel, ApiHttpError>(
    () => request<ProductModel, ApiHttpError>({
      ...params,
      path: `/api/products/${encodeURIComponent(String(pathParams["id"]))}/toggle-active`,
      method: "POST",
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      transformResponse: (value) => fromWireValue(value, typedApiWireSchemas["operation:ProductToggleProductActivePOSTApiProductsIdToggleActive:response"], typedApiWireSchemas) as ProductModel,
      transformError: (value, response) => createApiHttpError(response.status, value),
    },
  );
}

/**
 * No description
 *
 * @tags Product
 * @name ProductExportProducts
 * @request GET:/api/products/export
 */
export async function productExportProducts(
  query: ProductExportProductsParams = {},
  options: ApiMethodOptions<void, ApiHttpError, RequestParams> = {}
): Promise<ApiResult<void, ApiHttpError>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<void, ApiHttpError>(
    () => request<void, ApiHttpError>({
      ...params,
      path: `/api/products/export`,
      method: "GET",
      query: {
          "search": query["search"],
          "active": query["active"],
          "productIds": query["productIds"],
        },
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      transformError: (value, response) => createApiHttpError(response.status, value),
    },
  );
}
