/* eslint-disable */
/* tslint:disable */
/*
 * --------------------------------------------------------------------------------
 * ## THIS FILE WAS GENERATED BY typedapi-client-helpers                         ##
 * ##                                                                            ##
 * ## AUTHOR: Stef Buurman                                                       ##
 * ## SOURCE: https://github.com/Stef-Buurman/TypedApi/tree/main/npm/typed-api-client ##
 * --------------------------------------------------------------------------------
 */
import { ContentType, request } from "../generated/http-client";
import type { RequestParams } from "../generated/http-client";
import type {
  DeleteSupplierParams,
  GetSupplierByIdParams,
  GetSuppliersParams,
  SupplierModel,
  SupplierModelApiPaginationResponse,
  SupplierRequest,
  UpdateSupplierParams,
  VerifySupplierParams,
} from "../generated/data-contracts";
import { buildQuery, handleApiResponse } from "typedapi-client-helpers";
import type {
  ApiMethodOptions,
  ApiResult,
  ExtractDataIfPaginated,
  FilterFormValues,
  SortableKeys,
  SortDirection,
  UnwrapArray,
} from "typedapi-client-helpers";
import { handleGoodResult as typedApiDefaultSuccessHandler, handleErrors as typedApiDefaultErrorHandler } from "../../utils/defaultApiFunctions";

export type GetSuppliersQuery = NonNullable<GetSuppliersParams>;

/**
 * No description
 *
 * @tags Supplier
 * @name GetSuppliers
 * @request GET:/api/suppliers
 */
export async function getSuppliers(
  filters: FilterFormValues<GetSuppliersQuery>[] = [],
  page = 1,
  pageSize = 100,
  sortBy: SortableKeys<SupplierModelApiPaginationResponse> | null = null,
  sortDirection?: SortDirection,
  options: ApiMethodOptions<SupplierModelApiPaginationResponse, any, RequestParams> = {},
): Promise<ApiResult<SupplierModelApiPaginationResponse>> {
  const { onSuccess, onError, params } = options;
  const builtQuery = buildQuery<
    GetSuppliersQuery,
    UnwrapArray<ExtractDataIfPaginated<SupplierModelApiPaginationResponse>>
  >(filters, page, pageSize, sortBy, sortDirection);

  return handleApiResponse<SupplierModelApiPaginationResponse, any>(
    () => request<SupplierModelApiPaginationResponse, any>({
      path: `/api/suppliers`,
      method: "GET",
      query: builtQuery ?? {},
      format: "json",
      ...params,
    }),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler },
  );
}

/**
 * No description
 *
 * @tags Supplier
 * @name CreateSupplier
 * @request POST:/api/suppliers
 */
export async function createSupplier(
  data: SupplierRequest,
  options: ApiMethodOptions<SupplierModel, any, RequestParams> = {}
): Promise<ApiResult<SupplierModel>> {
  const { onSuccess, onError, params } = options;
  return handleApiResponse<SupplierModel, any>(
    () => request<SupplierModel, any>({
      path: `/api/suppliers`,
      method: "POST",
      body: data,
      type: ContentType.Json,
      format: "json",
      ...params,
    }),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler },
  );
}

/**
 * No description
 *
 * @tags Supplier
 * @name GetSupplierById
 * @request GET:/api/suppliers/{id}
 */
export async function getSupplierById(
  pathParams: GetSupplierByIdParams,
  options: ApiMethodOptions<SupplierModel, any, RequestParams> = {}
): Promise<ApiResult<SupplierModel>> {
  const { onSuccess, onError, params } = options;
  return handleApiResponse<SupplierModel, any>(
    () => request<SupplierModel, any>({
      path: `/api/suppliers/${encodeURIComponent(String(pathParams.id))}`,
      method: "GET",
      format: "json",
      ...params,
    }),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler },
  );
}

/**
 * No description
 *
 * @tags Supplier
 * @name UpdateSupplier
 * @request PUT:/api/suppliers/{id}
 */
export async function updateSupplier(
  pathParams: UpdateSupplierParams,
  data: SupplierRequest,
  options: ApiMethodOptions<SupplierModel, any, RequestParams> = {}
): Promise<ApiResult<SupplierModel>> {
  const { onSuccess, onError, params } = options;
  return handleApiResponse<SupplierModel, any>(
    () => request<SupplierModel, any>({
      path: `/api/suppliers/${encodeURIComponent(String(pathParams.id))}`,
      method: "PUT",
      body: data,
      type: ContentType.Json,
      format: "json",
      ...params,
    }),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler },
  );
}

/**
 * No description
 *
 * @tags Supplier
 * @name DeleteSupplier
 * @request DELETE:/api/suppliers/{id}
 */
export async function deleteSupplier(
  pathParams: DeleteSupplierParams,
  options: ApiMethodOptions<void, any, RequestParams> = {}
): Promise<ApiResult<void>> {
  const { onSuccess, onError, params } = options;
  return handleApiResponse<void, any>(
    () => request<void, any>({
      path: `/api/suppliers/${encodeURIComponent(String(pathParams.id))}`,
      method: "DELETE",
      ...params,
    }),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler },
  );
}

/**
 * No description
 *
 * @tags Supplier
 * @name VerifySupplier
 * @request POST:/api/suppliers/{id}/verify
 */
export async function verifySupplier(
  pathParams: VerifySupplierParams,
  options: ApiMethodOptions<SupplierModel, any, RequestParams> = {}
): Promise<ApiResult<SupplierModel>> {
  const { onSuccess, onError, params } = options;
  return handleApiResponse<SupplierModel, any>(
    () => request<SupplierModel, any>({
      path: `/api/suppliers/${encodeURIComponent(String(pathParams.id))}/verify`,
      method: "POST",
      format: "json",
      ...params,
    }),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler },
  );
}
