/* eslint-disable */
/* tslint:disable */
/*
 * -------------------------------------------------------------------------------------
 * ## THIS FILE WAS GENERATED BY typedapi-client-helpers                              ##
 * ## DO NOT EDIT THIS FILE DIRECTLY                                                  ##
 * ##                                                                                 ##
 * ## AUTHOR: Stef Buurman                                                            ##
 * ## SOURCE: https://github.com/Stef-Buurman/TypedApi/tree/main/npm/typed-api-client ##
 * -------------------------------------------------------------------------------------
 */
import { ContentType, request } from "../generated/http-client";
import type { RequestParams } from "../generated/http-client";
import type {
  ApiPaginationResponse,
  HttpValidationProblemDetails,
  ProblemDetails,
  SupplierDeleteSupplierParams,
  SupplierGetSupplierByIdParams,
  SupplierGetSuppliersQueryParams,
  SupplierModel,
  SupplierRequest,
  SupplierUpdateSupplierParams,
  SupplierVerifySupplierParams,
} from "../generated/data-contracts";
import { buildQuery, handleApiResponse } from "typedapi-client-helpers";
import type {
  ApiMethodOptions,
  ApiResult,
  ExtractDataIfPaginated,
  FilterFormValues,
  SortableKeys,
  SortDirection,
  UnwrapArray,
} from "typedapi-client-helpers";
import { handleGoodResult as typedApiDefaultSuccessHandler, handleErrors as typedApiDefaultErrorHandler, unknownErrorMessage as typedApiDefaultErrorMessage } from "../../utils/defaultApiFunctions";

/**
 * No description
 *
 * @tags Supplier
 * @name SupplierGetSuppliers
 * @request GET:/api/suppliers
 */
export async function supplierGetSuppliers(
  filters: FilterFormValues<SupplierGetSuppliersQueryParams>[] = [],
  page = 1,
  pageSize = 100,
  sortBy: SortableKeys<ApiPaginationResponse<SupplierModel>> | null = null,
  sortDirection?: SortDirection,
  options: ApiMethodOptions<ApiPaginationResponse<SupplierModel>, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails, RequestParams> = {},
): Promise<ApiResult<ApiPaginationResponse<SupplierModel>, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>> {
  const { onSuccess, onError, params = {} } = options;
  const builtQuery = buildQuery<
    SupplierGetSuppliersQueryParams,
    UnwrapArray<ExtractDataIfPaginated<ApiPaginationResponse<SupplierModel>>>
  >(filters, page, pageSize, sortBy, sortDirection);

  return handleApiResponse<ApiPaginationResponse<SupplierModel>, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>(
    () => request<ApiPaginationResponse<SupplierModel>, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>({
      ...params,
      path: `/api/suppliers`,
      method: "GET",
      query: builtQuery,
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      fallbackErrorMessage: typedApiDefaultErrorMessage,
    },
  );
}

/**
 * No description
 *
 * @tags Supplier
 * @name SupplierCreateSupplier
 * @request POST:/api/suppliers
 */
export async function supplierCreateSupplier(
  data: SupplierRequest,
  options: ApiMethodOptions<SupplierModel, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails, RequestParams> = {}
): Promise<ApiResult<SupplierModel, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<SupplierModel, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>(
    () => request<SupplierModel, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>({
      ...params,
      path: `/api/suppliers`,
      method: "POST",
      body: data,
      type: ContentType.Json,
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      fallbackErrorMessage: typedApiDefaultErrorMessage,
    },
  );
}

/**
 * No description
 *
 * @tags Supplier
 * @name SupplierGetSupplierById
 * @request GET:/api/suppliers/{id}
 */
export async function supplierGetSupplierById(
  pathParams: SupplierGetSupplierByIdParams,
  options: ApiMethodOptions<SupplierModel, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails, RequestParams> = {}
): Promise<ApiResult<SupplierModel, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<SupplierModel, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>(
    () => request<SupplierModel, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>({
      ...params,
      path: `/api/suppliers/${encodeURIComponent(String(pathParams["id"]))}`,
      method: "GET",
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      fallbackErrorMessage: typedApiDefaultErrorMessage,
    },
  );
}

/**
 * No description
 *
 * @tags Supplier
 * @name SupplierUpdateSupplier
 * @request PUT:/api/suppliers/{id}
 */
export async function supplierUpdateSupplier(
  pathParams: SupplierUpdateSupplierParams,
  data: SupplierRequest,
  options: ApiMethodOptions<SupplierModel, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails, RequestParams> = {}
): Promise<ApiResult<SupplierModel, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<SupplierModel, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>(
    () => request<SupplierModel, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>({
      ...params,
      path: `/api/suppliers/${encodeURIComponent(String(pathParams["id"]))}`,
      method: "PUT",
      body: data,
      type: ContentType.Json,
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      fallbackErrorMessage: typedApiDefaultErrorMessage,
    },
  );
}

/**
 * No description
 *
 * @tags Supplier
 * @name SupplierDeleteSupplier
 * @request DELETE:/api/suppliers/{id}
 */
export async function supplierDeleteSupplier(
  pathParams: SupplierDeleteSupplierParams,
  options: ApiMethodOptions<void, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails, RequestParams> = {}
): Promise<ApiResult<void, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<void, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>(
    () => request<void, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>({
      ...params,
      path: `/api/suppliers/${encodeURIComponent(String(pathParams["id"]))}`,
      method: "DELETE",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      fallbackErrorMessage: typedApiDefaultErrorMessage,
    },
  );
}

/**
 * No description
 *
 * @tags Supplier
 * @name SupplierVerifySupplier
 * @request POST:/api/suppliers/{id}/verify
 */
export async function supplierVerifySupplier(
  pathParams: SupplierVerifySupplierParams,
  options: ApiMethodOptions<SupplierModel, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails, RequestParams> = {}
): Promise<ApiResult<SupplierModel, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<SupplierModel, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>(
    () => request<SupplierModel, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>({
      ...params,
      path: `/api/suppliers/${encodeURIComponent(String(pathParams["id"]))}/verify`,
      method: "POST",
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      fallbackErrorMessage: typedApiDefaultErrorMessage,
    },
  );
}
