/* eslint-disable */
/* tslint:disable */
/*
 * -------------------------------------------------------------------------------------
 * ## THIS FILE WAS GENERATED BY typedapi-client-helpers                              ##
 * ## DO NOT EDIT THIS FILE DIRECTLY                                                  ##
 * ##                                                                                 ##
 * ## AUTHOR: Stef Buurman                                                            ##
 * ## SOURCE: https://github.com/Stef-Buurman/TypedApi/tree/main/npm/typed-api-client ##
 * -------------------------------------------------------------------------------------
 */
import { ContentType, request } from "../generated/http-client";
import type { RequestParams } from "../generated/http-client";
import { typedApiWireSchemas } from "../generated/data-contracts";
import type {
  SupplierDeleteSupplierParams,
  SupplierGetSupplierByIdParams,
  SupplierGetSuppliersQueryParams,
  SupplierModel,
  SupplierModelApiPaginationResponse,
  SupplierRequest,
  SupplierUpdateSupplierParams,
  SupplierVerifySupplierParams,
} from "../generated/data-contracts";
import {
  buildQuery,
  fromWireValue,
  handleApiResponse,
  toWireValue,
} from "typedapi-client-helpers";
import type {
  ApiMethodOptions,
  ApiResult,
  ExtractDataIfPaginated,
  FilterFormValues,
  SortableKeys,
  SortDirection,
  UnwrapArray,
} from "typedapi-client-helpers";
import { handleGoodResult as typedApiDefaultSuccessHandler, handleErrors as typedApiDefaultErrorHandler } from "../../utils/defaultApiFunctions";

/**
 * No description
 *
 * @tags Supplier
 * @name SupplierGetSuppliers
 * @request GET:/api/suppliers
 */
export async function supplierGetSuppliers(
  filters: FilterFormValues<SupplierGetSuppliersQueryParams>[] = [],
  page = 1,
  pageSize = 100,
  sortBy: SortableKeys<SupplierModelApiPaginationResponse> | null = null,
  sortDirection?: SortDirection,
  options: ApiMethodOptions<SupplierModelApiPaginationResponse, unknown, RequestParams> = {},
): Promise<ApiResult<SupplierModelApiPaginationResponse, unknown>> {
  const { onSuccess, onError, params = {} } = options;
  const builtQuery = buildQuery<
    SupplierGetSuppliersQueryParams,
    UnwrapArray<ExtractDataIfPaginated<SupplierModelApiPaginationResponse>>
  >(filters, page, pageSize, sortBy, sortDirection);

  return handleApiResponse<SupplierModelApiPaginationResponse, unknown>(
    () => request<SupplierModelApiPaginationResponse, unknown>({
      ...params,
      path: `/api/suppliers`,
      method: "GET",
      query: builtQuery,
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      transformResponse: (value) => fromWireValue(value, typedApiWireSchemas["operation:SupplierGetSuppliersGETApiSuppliers:response"], typedApiWireSchemas) as SupplierModelApiPaginationResponse,
    },
  );
}

/**
 * No description
 *
 * @tags Supplier
 * @name SupplierCreateSupplier
 * @request POST:/api/suppliers
 */
export async function supplierCreateSupplier(
  data: SupplierRequest,
  options: ApiMethodOptions<SupplierModel, unknown, RequestParams> = {}
): Promise<ApiResult<SupplierModel, unknown>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<SupplierModel, unknown>(
    () => request<SupplierModel, unknown>({
      ...params,
      path: `/api/suppliers`,
      method: "POST",
      body: toWireValue(data, typedApiWireSchemas["operation:SupplierCreateSupplierPOSTApiSuppliers:body"], typedApiWireSchemas),
      type: ContentType.Json,
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      transformResponse: (value) => fromWireValue(value, typedApiWireSchemas["operation:SupplierCreateSupplierPOSTApiSuppliers:response"], typedApiWireSchemas) as SupplierModel,
    },
  );
}

/**
 * No description
 *
 * @tags Supplier
 * @name SupplierGetSupplierById
 * @request GET:/api/suppliers/{id}
 */
export async function supplierGetSupplierById(
  pathParams: SupplierGetSupplierByIdParams,
  options: ApiMethodOptions<SupplierModel, unknown, RequestParams> = {}
): Promise<ApiResult<SupplierModel, unknown>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<SupplierModel, unknown>(
    () => request<SupplierModel, unknown>({
      ...params,
      path: `/api/suppliers/${encodeURIComponent(String(pathParams["id"]))}`,
      method: "GET",
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      transformResponse: (value) => fromWireValue(value, typedApiWireSchemas["operation:SupplierGetSupplierByIdGETApiSuppliersId:response"], typedApiWireSchemas) as SupplierModel,
    },
  );
}

/**
 * No description
 *
 * @tags Supplier
 * @name SupplierUpdateSupplier
 * @request PUT:/api/suppliers/{id}
 */
export async function supplierUpdateSupplier(
  pathParams: SupplierUpdateSupplierParams,
  data: SupplierRequest,
  options: ApiMethodOptions<SupplierModel, unknown, RequestParams> = {}
): Promise<ApiResult<SupplierModel, unknown>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<SupplierModel, unknown>(
    () => request<SupplierModel, unknown>({
      ...params,
      path: `/api/suppliers/${encodeURIComponent(String(pathParams["id"]))}`,
      method: "PUT",
      body: toWireValue(data, typedApiWireSchemas["operation:SupplierUpdateSupplierPUTApiSuppliersId:body"], typedApiWireSchemas),
      type: ContentType.Json,
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      transformResponse: (value) => fromWireValue(value, typedApiWireSchemas["operation:SupplierUpdateSupplierPUTApiSuppliersId:response"], typedApiWireSchemas) as SupplierModel,
    },
  );
}

/**
 * No description
 *
 * @tags Supplier
 * @name SupplierDeleteSupplier
 * @request DELETE:/api/suppliers/{id}
 */
export async function supplierDeleteSupplier(
  pathParams: SupplierDeleteSupplierParams,
  options: ApiMethodOptions<void, unknown, RequestParams> = {}
): Promise<ApiResult<void, unknown>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<void, unknown>(
    () => request<void, unknown>({
      ...params,
      path: `/api/suppliers/${encodeURIComponent(String(pathParams["id"]))}`,
      method: "DELETE",
    }),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler },
  );
}

/**
 * No description
 *
 * @tags Supplier
 * @name SupplierVerifySupplier
 * @request POST:/api/suppliers/{id}/verify
 */
export async function supplierVerifySupplier(
  pathParams: SupplierVerifySupplierParams,
  options: ApiMethodOptions<SupplierModel, unknown, RequestParams> = {}
): Promise<ApiResult<SupplierModel, unknown>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<SupplierModel, unknown>(
    () => request<SupplierModel, unknown>({
      ...params,
      path: `/api/suppliers/${encodeURIComponent(String(pathParams["id"]))}/verify`,
      method: "POST",
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      transformResponse: (value) => fromWireValue(value, typedApiWireSchemas["operation:SupplierVerifySupplierPOSTApiSuppliersIdVerify:response"], typedApiWireSchemas) as SupplierModel,
    },
  );
}
