/* eslint-disable */
/* tslint:disable */
/*
 * -------------------------------------------------------------------------------------
 * ## THIS FILE WAS GENERATED BY typedapi-client-helpers                              ##
 * ## DO NOT EDIT THIS FILE DIRECTLY                                                  ##
 * ##                                                                                 ##
 * ## AUTHOR: Stef Buurman                                                            ##
 * ## SOURCE: https://github.com/Stef-Buurman/TypedApi/tree/main/npm/typed-api-client ##
 * -------------------------------------------------------------------------------------
 */
import { ContentType, request } from "../generated/http-client";
import type { RequestParams } from "../generated/http-client";
import type {
  ApiEnvelope,
  ApiPaginationSortResponse,
  EmailNotificationModel,
  HttpValidationProblemDetails,
  NullabilityContract,
  ProblemDetails,
  ProjectModel,
  SmsNotificationModel,
  TeamMemberModel,
  TypedApiFeaturesGetProjectWithTypedErrorsParams,
} from "../generated/data-contracts";
import { handleApiResponse } from "typedapi-client-helpers";
import type { ApiMethodOptions, ApiResult } from "typedapi-client-helpers";
import { handleGoodResult as typedApiDefaultSuccessHandler, handleErrors as typedApiDefaultErrorHandler, unknownErrorMessage as typedApiDefaultErrorMessage } from "../../utils/defaultApiFunctions";

/**
 * No description
 *
 * @tags TypedApiFeatures
 * @name TypedApiFeaturesGetProjects
 * @request GET:/api/typed-api-features/projects
 */
export async function typedApiFeaturesGetProjects(
  options: ApiMethodOptions<ApiPaginationSortResponse<ProjectModel>, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails, RequestParams> = {}
): Promise<ApiResult<ApiPaginationSortResponse<ProjectModel>, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<ApiPaginationSortResponse<ProjectModel>, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>(
    () => request<ApiPaginationSortResponse<ProjectModel>, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>({
      ...params,
      path: `/api/typed-api-features/projects`,
      method: "GET",
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      fallbackErrorMessage: typedApiDefaultErrorMessage,
    },
  );
}

/**
 * No description
 *
 * @tags TypedApiFeatures
 * @name TypedApiFeaturesGetTeamMemberEnvelope
 * @request GET:/api/typed-api-features/team-member-envelope
 */
export async function typedApiFeaturesGetTeamMemberEnvelope(
  options: ApiMethodOptions<ApiEnvelope<TeamMemberModel>, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails, RequestParams> = {}
): Promise<ApiResult<ApiEnvelope<TeamMemberModel>, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<ApiEnvelope<TeamMemberModel>, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>(
    () => request<ApiEnvelope<TeamMemberModel>, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>({
      ...params,
      path: `/api/typed-api-features/team-member-envelope`,
      method: "GET",
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      fallbackErrorMessage: typedApiDefaultErrorMessage,
    },
  );
}

/**
 * No description
 *
 * @tags TypedApiFeatures
 * @name TypedApiFeaturesGetNullability
 * @request GET:/api/typed-api-features/nullability
 */
export async function typedApiFeaturesGetNullability(
  options: ApiMethodOptions<NullabilityContract, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails, RequestParams> = {}
): Promise<ApiResult<NullabilityContract, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<NullabilityContract, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>(
    () => request<NullabilityContract, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>({
      ...params,
      path: `/api/typed-api-features/nullability`,
      method: "GET",
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      fallbackErrorMessage: typedApiDefaultErrorMessage,
    },
  );
}

/**
 * No description
 *
 * @tags TypedApiFeatures
 * @name TypedApiFeaturesEchoNullability
 * @request POST:/api/typed-api-features/nullability
 */
export async function typedApiFeaturesEchoNullability(
  data: NullabilityContract,
  options: ApiMethodOptions<NullabilityContract, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails, RequestParams> = {}
): Promise<ApiResult<NullabilityContract, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<NullabilityContract, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>(
    () => request<NullabilityContract, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>({
      ...params,
      path: `/api/typed-api-features/nullability`,
      method: "POST",
      body: data,
      type: ContentType.Json,
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      fallbackErrorMessage: typedApiDefaultErrorMessage,
    },
  );
}

/**
 * No description
 *
 * @tags TypedApiFeatures
 * @name TypedApiFeaturesGetNotification
 * @request GET:/api/typed-api-features/notification
 */
export async function typedApiFeaturesGetNotification(
  options: ApiMethodOptions<EmailNotificationModel | SmsNotificationModel, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails, RequestParams> = {}
): Promise<ApiResult<EmailNotificationModel | SmsNotificationModel, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<EmailNotificationModel | SmsNotificationModel, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>(
    () => request<EmailNotificationModel | SmsNotificationModel, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>({
      ...params,
      path: `/api/typed-api-features/notification`,
      method: "GET",
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      fallbackErrorMessage: typedApiDefaultErrorMessage,
    },
  );
}

/**
 * No description
 *
 * @tags TypedApiFeatures
 * @name TypedApiFeaturesEchoNotification
 * @request POST:/api/typed-api-features/notification
 */
export async function typedApiFeaturesEchoNotification(
  data: EmailNotificationModel | SmsNotificationModel,
  options: ApiMethodOptions<EmailNotificationModel | SmsNotificationModel, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails, RequestParams> = {}
): Promise<ApiResult<EmailNotificationModel | SmsNotificationModel, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<EmailNotificationModel | SmsNotificationModel, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>(
    () => request<EmailNotificationModel | SmsNotificationModel, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>({
      ...params,
      path: `/api/typed-api-features/notification`,
      method: "POST",
      body: data,
      type: ContentType.Json,
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      fallbackErrorMessage: typedApiDefaultErrorMessage,
    },
  );
}

/**
 * No description
 *
 * @tags TypedApiFeatures
 * @name TypedApiFeaturesGetProjectWithTypedErrors
 * @request GET:/api/typed-api-features/projects/{id}
 */
export async function typedApiFeaturesGetProjectWithTypedErrors(
  pathParams: TypedApiFeaturesGetProjectWithTypedErrorsParams,
  options: ApiMethodOptions<ProjectModel, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails, RequestParams> = {}
): Promise<ApiResult<ProjectModel, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<ProjectModel, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>(
    () => request<ProjectModel, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>({
      ...params,
      path: `/api/typed-api-features/projects/${encodeURIComponent(String(pathParams["id"]))}`,
      method: "GET",
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      fallbackErrorMessage: typedApiDefaultErrorMessage,
    },
  );
}
