/* eslint-disable */
/* tslint:disable */
/*
 * -------------------------------------------------------------------------------------
 * ## THIS FILE WAS GENERATED BY typedapi-client-helpers                              ##
 * ## DO NOT EDIT THIS FILE DIRECTLY                                                  ##
 * ##                                                                                 ##
 * ## AUTHOR: Stef Buurman                                                            ##
 * ## SOURCE: https://github.com/Stef-Buurman/TypedApi/tree/main/npm/typed-api-client ##
 * -------------------------------------------------------------------------------------
 */
import { ContentType, request } from "../generated/http-client";
import type { RequestParams } from "../generated/http-client";
import { typedApiWireSchemas } from "../generated/data-contracts";
import type {
  WarehouseDeleteWarehouseParams,
  WarehouseGetWarehouseByIdParams,
  WarehouseGetWarehousesQueryParams,
  WarehouseModel,
  WarehouseModelApiPaginationResponse,
  WarehouseRequest,
  WarehouseUpdateWarehouseParams,
} from "../generated/data-contracts";
import {
  buildQuery,
  createApiHttpError,
  fromWireValue,
  handleApiResponse,
  toWireValue,
} from "typedapi-client-helpers";
import type {
  ApiHttpError,
  ApiMethodOptions,
  ApiResult,
  ExtractDataIfPaginated,
  FilterFormValues,
  SortableKeys,
  SortDirection,
  UnwrapArray,
} from "typedapi-client-helpers";
import { handleGoodResult as typedApiDefaultSuccessHandler, handleErrors as typedApiDefaultErrorHandler } from "../../utils/defaultApiFunctions";

/**
 * No description
 *
 * @tags Warehouse
 * @name WarehouseGetWarehouses
 * @request GET:/api/warehouses
 */
export async function warehouseGetWarehouses(
  filters: FilterFormValues<WarehouseGetWarehousesQueryParams>[] = [],
  page = 1,
  pageSize = 100,
  sortBy: SortableKeys<WarehouseModelApiPaginationResponse> | null = null,
  sortDirection?: SortDirection,
  options: ApiMethodOptions<WarehouseModelApiPaginationResponse, ApiHttpError, RequestParams> = {},
): Promise<ApiResult<WarehouseModelApiPaginationResponse, ApiHttpError>> {
  const { onSuccess, onError, params = {} } = options;
  const builtQuery = buildQuery<
    WarehouseGetWarehousesQueryParams,
    UnwrapArray<ExtractDataIfPaginated<WarehouseModelApiPaginationResponse>>
  >(filters, page, pageSize, sortBy, sortDirection);

  return handleApiResponse<WarehouseModelApiPaginationResponse, ApiHttpError>(
    () => request<WarehouseModelApiPaginationResponse, ApiHttpError>({
      ...params,
      path: `/api/warehouses`,
      method: "GET",
      query: builtQuery,
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      transformResponse: (value) => fromWireValue(value, typedApiWireSchemas["operation:WarehouseGetWarehousesGETApiWarehouses:response"], typedApiWireSchemas) as WarehouseModelApiPaginationResponse,
      transformError: (value, response) => createApiHttpError(response.status, value),
    },
  );
}

/**
 * No description
 *
 * @tags Warehouse
 * @name WarehouseCreateWarehouse
 * @request POST:/api/warehouses
 */
export async function warehouseCreateWarehouse(
  data: WarehouseRequest,
  options: ApiMethodOptions<WarehouseModel, ApiHttpError, RequestParams> = {}
): Promise<ApiResult<WarehouseModel, ApiHttpError>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<WarehouseModel, ApiHttpError>(
    () => request<WarehouseModel, ApiHttpError>({
      ...params,
      path: `/api/warehouses`,
      method: "POST",
      body: toWireValue(data, typedApiWireSchemas["operation:WarehouseCreateWarehousePOSTApiWarehouses:body"], typedApiWireSchemas),
      type: ContentType.Json,
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      transformResponse: (value) => fromWireValue(value, typedApiWireSchemas["operation:WarehouseCreateWarehousePOSTApiWarehouses:response"], typedApiWireSchemas) as WarehouseModel,
      transformError: (value, response) => createApiHttpError(response.status, value),
    },
  );
}

/**
 * No description
 *
 * @tags Warehouse
 * @name WarehouseGetWarehouseById
 * @request GET:/api/warehouses/{id}
 */
export async function warehouseGetWarehouseById(
  pathParams: WarehouseGetWarehouseByIdParams,
  options: ApiMethodOptions<WarehouseModel, ApiHttpError, RequestParams> = {}
): Promise<ApiResult<WarehouseModel, ApiHttpError>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<WarehouseModel, ApiHttpError>(
    () => request<WarehouseModel, ApiHttpError>({
      ...params,
      path: `/api/warehouses/${encodeURIComponent(String(pathParams["id"]))}`,
      method: "GET",
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      transformResponse: (value) => fromWireValue(value, typedApiWireSchemas["operation:WarehouseGetWarehouseByIdGETApiWarehousesId:response"], typedApiWireSchemas) as WarehouseModel,
      transformError: (value, response) => createApiHttpError(response.status, value),
    },
  );
}

/**
 * No description
 *
 * @tags Warehouse
 * @name WarehouseUpdateWarehouse
 * @request PUT:/api/warehouses/{id}
 */
export async function warehouseUpdateWarehouse(
  pathParams: WarehouseUpdateWarehouseParams,
  data: WarehouseRequest,
  options: ApiMethodOptions<WarehouseModel, ApiHttpError, RequestParams> = {}
): Promise<ApiResult<WarehouseModel, ApiHttpError>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<WarehouseModel, ApiHttpError>(
    () => request<WarehouseModel, ApiHttpError>({
      ...params,
      path: `/api/warehouses/${encodeURIComponent(String(pathParams["id"]))}`,
      method: "PUT",
      body: toWireValue(data, typedApiWireSchemas["operation:WarehouseUpdateWarehousePUTApiWarehousesId:body"], typedApiWireSchemas),
      type: ContentType.Json,
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      transformResponse: (value) => fromWireValue(value, typedApiWireSchemas["operation:WarehouseUpdateWarehousePUTApiWarehousesId:response"], typedApiWireSchemas) as WarehouseModel,
      transformError: (value, response) => createApiHttpError(response.status, value),
    },
  );
}

/**
 * No description
 *
 * @tags Warehouse
 * @name WarehouseDeleteWarehouse
 * @request DELETE:/api/warehouses/{id}
 */
export async function warehouseDeleteWarehouse(
  pathParams: WarehouseDeleteWarehouseParams,
  options: ApiMethodOptions<void, ApiHttpError, RequestParams> = {}
): Promise<ApiResult<void, ApiHttpError>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<void, ApiHttpError>(
    () => request<void, ApiHttpError>({
      ...params,
      path: `/api/warehouses/${encodeURIComponent(String(pathParams["id"]))}`,
      method: "DELETE",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      transformError: (value, response) => createApiHttpError(response.status, value),
    },
  );
}
