/* eslint-disable */
/* tslint:disable */
/*
 * -------------------------------------------------------------------------------------
 * ## THIS FILE WAS GENERATED BY typedapi-client-helpers                              ##
 * ## DO NOT EDIT THIS FILE DIRECTLY                                                  ##
 * ##                                                                                 ##
 * ## AUTHOR: Stef Buurman                                                            ##
 * ## SOURCE: https://github.com/Stef-Buurman/TypedApi/tree/main/npm/typed-api-client ##
 * -------------------------------------------------------------------------------------
 */
import { ContentType, request } from "../generated/http-client";
import type { RequestParams } from "../generated/http-client";
import type {
  ApiPaginationResponse,
  HttpValidationProblemDetails,
  ProblemDetails,
  WarehouseDeleteWarehouseParams,
  WarehouseGetWarehouseByIdParams,
  WarehouseGetWarehousesQueryParams,
  WarehouseModel,
  WarehouseRequest,
  WarehouseUpdateWarehouseParams,
} from "../generated/data-contracts";
import { buildQuery, handleApiResponse } from "typedapi-client-helpers";
import type {
  ApiMethodOptions,
  ApiResult,
  ExtractDataIfPaginated,
  FilterFormValues,
  SortableKeys,
  SortDirection,
  UnwrapArray,
} from "typedapi-client-helpers";
import { handleGoodResult as typedApiDefaultSuccessHandler, handleErrors as typedApiDefaultErrorHandler, unknownErrorMessage as typedApiDefaultErrorMessage } from "../../utils/defaultApiFunctions";

/**
 * No description
 *
 * @tags Warehouse
 * @name WarehouseGetWarehouses
 * @request GET:/api/warehouses
 */
export async function warehouseGetWarehouses(
  filters: FilterFormValues<WarehouseGetWarehousesQueryParams>[] = [],
  page = 1,
  pageSize = 100,
  sortBy: SortableKeys<ApiPaginationResponse<WarehouseModel>> | null = null,
  sortDirection?: SortDirection,
  options: ApiMethodOptions<ApiPaginationResponse<WarehouseModel>, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails, RequestParams> = {},
): Promise<ApiResult<ApiPaginationResponse<WarehouseModel>, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>> {
  const { onSuccess, onError, params = {} } = options;
  const builtQuery = buildQuery<
    WarehouseGetWarehousesQueryParams,
    UnwrapArray<ExtractDataIfPaginated<ApiPaginationResponse<WarehouseModel>>>
  >(filters, page, pageSize, sortBy, sortDirection);

  return handleApiResponse<ApiPaginationResponse<WarehouseModel>, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>(
    () => request<ApiPaginationResponse<WarehouseModel>, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>({
      ...params,
      path: `/api/warehouses`,
      method: "GET",
      query: builtQuery,
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      fallbackErrorMessage: typedApiDefaultErrorMessage,
    },
  );
}

/**
 * No description
 *
 * @tags Warehouse
 * @name WarehouseCreateWarehouse
 * @request POST:/api/warehouses
 */
export async function warehouseCreateWarehouse(
  data: WarehouseRequest,
  options: ApiMethodOptions<WarehouseModel, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails, RequestParams> = {}
): Promise<ApiResult<WarehouseModel, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<WarehouseModel, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>(
    () => request<WarehouseModel, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>({
      ...params,
      path: `/api/warehouses`,
      method: "POST",
      body: data,
      type: ContentType.Json,
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      fallbackErrorMessage: typedApiDefaultErrorMessage,
    },
  );
}

/**
 * No description
 *
 * @tags Warehouse
 * @name WarehouseGetWarehouseById
 * @request GET:/api/warehouses/{id}
 */
export async function warehouseGetWarehouseById(
  pathParams: WarehouseGetWarehouseByIdParams,
  options: ApiMethodOptions<WarehouseModel, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails, RequestParams> = {}
): Promise<ApiResult<WarehouseModel, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<WarehouseModel, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>(
    () => request<WarehouseModel, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>({
      ...params,
      path: `/api/warehouses/${encodeURIComponent(String(pathParams["id"]))}`,
      method: "GET",
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      fallbackErrorMessage: typedApiDefaultErrorMessage,
    },
  );
}

/**
 * No description
 *
 * @tags Warehouse
 * @name WarehouseUpdateWarehouse
 * @request PUT:/api/warehouses/{id}
 */
export async function warehouseUpdateWarehouse(
  pathParams: WarehouseUpdateWarehouseParams,
  data: WarehouseRequest,
  options: ApiMethodOptions<WarehouseModel, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails, RequestParams> = {}
): Promise<ApiResult<WarehouseModel, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<WarehouseModel, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>(
    () => request<WarehouseModel, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>({
      ...params,
      path: `/api/warehouses/${encodeURIComponent(String(pathParams["id"]))}`,
      method: "PUT",
      body: data,
      type: ContentType.Json,
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      fallbackErrorMessage: typedApiDefaultErrorMessage,
    },
  );
}

/**
 * No description
 *
 * @tags Warehouse
 * @name WarehouseDeleteWarehouse
 * @request DELETE:/api/warehouses/{id}
 */
export async function warehouseDeleteWarehouse(
  pathParams: WarehouseDeleteWarehouseParams,
  options: ApiMethodOptions<void, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails, RequestParams> = {}
): Promise<ApiResult<void, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<void, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>(
    () => request<void, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>({
      ...params,
      path: `/api/warehouses/${encodeURIComponent(String(pathParams["id"]))}`,
      method: "DELETE",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      fallbackErrorMessage: typedApiDefaultErrorMessage,
    },
  );
}
