/* eslint-disable */
/* tslint:disable */
/*
 * -------------------------------------------------------------------------------------
 * ## THIS FILE WAS GENERATED BY typedapi-client-helpers                              ##
 * ## DO NOT EDIT THIS FILE DIRECTLY                                                  ##
 * ##                                                                                 ##
 * ## AUTHOR: Stef Buurman                                                            ##
 * ## SOURCE: https://github.com/Stef-Buurman/TypedApi/tree/main/npm/typed-api-client ##
 * -------------------------------------------------------------------------------------
 */
import { ContentType, request } from "../generated/http-client";
import type { RequestParams } from "../generated/http-client";
import { typedApiWireSchemas } from "../generated/data-contracts";
import type {
  DeleteWarehouseParams,
  GetWarehouseByIdParams,
  GetWarehousesQueryParams,
  UpdateWarehouseParams,
  WarehouseModel,
  WarehouseModelApiPaginationResponse,
  WarehouseRequest,
} from "../generated/data-contracts";
import {
  buildQuery,
  fromWireValue,
  handleApiResponse,
  toWireValue,
} from "typedapi-client-helpers";
import type {
  ApiMethodOptions,
  ApiResult,
  ExtractDataIfPaginated,
  FilterFormValues,
  SortableKeys,
  SortDirection,
  UnwrapArray,
} from "typedapi-client-helpers";
import { handleGoodResult as typedApiDefaultSuccessHandler, handleErrors as typedApiDefaultErrorHandler } from "../../utils/defaultApiFunctions";

/**
 * No description
 *
 * @tags Warehouse
 * @name GetWarehouses
 * @request GET:/api/warehouses
 */
export async function getWarehouses(
  filters: FilterFormValues<GetWarehousesQueryParams>[] = [],
  page = 1,
  pageSize = 100,
  sortBy: SortableKeys<WarehouseModelApiPaginationResponse> | null = null,
  sortDirection?: SortDirection,
  options: ApiMethodOptions<WarehouseModelApiPaginationResponse, unknown, RequestParams> = {},
): Promise<ApiResult<WarehouseModelApiPaginationResponse, unknown>> {
  const { onSuccess, onError, params = {} } = options;
  const builtQuery = buildQuery<
    GetWarehousesQueryParams,
    UnwrapArray<ExtractDataIfPaginated<WarehouseModelApiPaginationResponse>>
  >(filters, page, pageSize, sortBy, sortDirection);

  return handleApiResponse<WarehouseModelApiPaginationResponse, unknown>(
    () => request<WarehouseModelApiPaginationResponse, unknown>({
      ...params,
      path: `/api/warehouses`,
      method: "GET",
      query: builtQuery,
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      transformResponse: (value) => fromWireValue(value, typedApiWireSchemas["operation:WarehouseGetWarehousesGETApiWarehouses:response"], typedApiWireSchemas) as WarehouseModelApiPaginationResponse,
    },
  );
}

/**
 * No description
 *
 * @tags Warehouse
 * @name CreateWarehouse
 * @request POST:/api/warehouses
 */
export async function createWarehouse(
  data: WarehouseRequest,
  options: ApiMethodOptions<WarehouseModel, unknown, RequestParams> = {}
): Promise<ApiResult<WarehouseModel, unknown>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<WarehouseModel, unknown>(
    () => request<WarehouseModel, unknown>({
      ...params,
      path: `/api/warehouses`,
      method: "POST",
      body: toWireValue(data, typedApiWireSchemas["operation:WarehouseCreateWarehousePOSTApiWarehouses:body"], typedApiWireSchemas),
      type: ContentType.Json,
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      transformResponse: (value) => fromWireValue(value, typedApiWireSchemas["operation:WarehouseCreateWarehousePOSTApiWarehouses:response"], typedApiWireSchemas) as WarehouseModel,
    },
  );
}

/**
 * No description
 *
 * @tags Warehouse
 * @name GetWarehouseById
 * @request GET:/api/warehouses/{id}
 */
export async function getWarehouseById(
  pathParams: GetWarehouseByIdParams,
  options: ApiMethodOptions<WarehouseModel, unknown, RequestParams> = {}
): Promise<ApiResult<WarehouseModel, unknown>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<WarehouseModel, unknown>(
    () => request<WarehouseModel, unknown>({
      ...params,
      path: `/api/warehouses/${encodeURIComponent(String(pathParams["id"]))}`,
      method: "GET",
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      transformResponse: (value) => fromWireValue(value, typedApiWireSchemas["operation:WarehouseGetWarehouseByIdGETApiWarehousesId:response"], typedApiWireSchemas) as WarehouseModel,
    },
  );
}

/**
 * No description
 *
 * @tags Warehouse
 * @name UpdateWarehouse
 * @request PUT:/api/warehouses/{id}
 */
export async function updateWarehouse(
  pathParams: UpdateWarehouseParams,
  data: WarehouseRequest,
  options: ApiMethodOptions<WarehouseModel, unknown, RequestParams> = {}
): Promise<ApiResult<WarehouseModel, unknown>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<WarehouseModel, unknown>(
    () => request<WarehouseModel, unknown>({
      ...params,
      path: `/api/warehouses/${encodeURIComponent(String(pathParams["id"]))}`,
      method: "PUT",
      body: toWireValue(data, typedApiWireSchemas["operation:WarehouseUpdateWarehousePUTApiWarehousesId:body"], typedApiWireSchemas),
      type: ContentType.Json,
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      transformResponse: (value) => fromWireValue(value, typedApiWireSchemas["operation:WarehouseUpdateWarehousePUTApiWarehousesId:response"], typedApiWireSchemas) as WarehouseModel,
    },
  );
}

/**
 * No description
 *
 * @tags Warehouse
 * @name DeleteWarehouse
 * @request DELETE:/api/warehouses/{id}
 */
export async function deleteWarehouse(
  pathParams: DeleteWarehouseParams,
  options: ApiMethodOptions<void, unknown, RequestParams> = {}
): Promise<ApiResult<void, unknown>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<void, unknown>(
    () => request<void, unknown>({
      ...params,
      path: `/api/warehouses/${encodeURIComponent(String(pathParams["id"]))}`,
      method: "DELETE",
    }),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler },
  );
}
