/* eslint-disable */
/* tslint:disable */
// This file was generated by typedapi-client-helpers. Do not edit manually.

import { ContentType, HttpClient } from "../http-client";
import type { RequestParams } from "../http-client";
import type { ApiResult, ApiMethodOptions } from "typedapi-client-helpers";
import { handleApiResponse } from "typedapi-client-helpers";
import type * as Contracts from "../data-contracts";
import { handleGoodResult as typedApiDefaultSuccessHandler, handleErrors as typedApiDefaultErrorHandler } from "../../utils/defaultApiFunctions";

export type UploadProductFilesBody = {
  Files?: File[];
};

export type UploadSupplierFileBody = {
  File?: File;
};

export type UploadMixedImportBody = {
  Files?: File[];
  ImportName?: string;
  ValidateOnly?: boolean;
};

export class ImportApi {
  private readonly http: HttpClient;

  constructor(http: HttpClient = new HttpClient()) {
    this.http = http;
  }

  public uploadProductFilesRaw = (
    data?: UploadProductFilesBody,
    params: RequestParams = {}
  ): Promise<import("../http-client").HttpResponse<Contracts.UploadResult, unknown>> => {
    return this.http.request<Contracts.UploadResult, unknown>({
      path: "/api/imports/products",
      method: "POST",
      body: data,
      type: ContentType.FormData,
      format: "json",
      ...params,
    });
  };

  public uploadSupplierFileRaw = (
    data?: UploadSupplierFileBody,
    params: RequestParams = {}
  ): Promise<import("../http-client").HttpResponse<Contracts.UploadResult, unknown>> => {
    return this.http.request<Contracts.UploadResult, unknown>({
      path: "/api/imports/supplier",
      method: "POST",
      body: data,
      type: ContentType.FormData,
      format: "json",
      ...params,
    });
  };

  public uploadMixedImportRaw = (
    data?: UploadMixedImportBody,
    params: RequestParams = {}
  ): Promise<import("../http-client").HttpResponse<Contracts.UploadResult, unknown>> => {
    return this.http.request<Contracts.UploadResult, unknown>({
      path: "/api/imports/mixed",
      method: "POST",
      body: data,
      type: ContentType.FormData,
      format: "json",
      ...params,
    });
  };
}

const importApi = new ImportApi();

export async function uploadProductFiles(
  data?: UploadProductFilesBody,
  options: ApiMethodOptions<Contracts.UploadResult, unknown, RequestParams> = {}
): Promise<ApiResult<Contracts.UploadResult>> {
  const { onSuccess, onError, params } = options;

  return handleApiResponse<Contracts.UploadResult, unknown>(
    () => importApi.uploadProductFilesRaw(data as any, params ?? {}),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler }
  );
}

export async function uploadSupplierFile(
  data?: UploadSupplierFileBody,
  options: ApiMethodOptions<Contracts.UploadResult, unknown, RequestParams> = {}
): Promise<ApiResult<Contracts.UploadResult>> {
  const { onSuccess, onError, params } = options;

  return handleApiResponse<Contracts.UploadResult, unknown>(
    () => importApi.uploadSupplierFileRaw(data as any, params ?? {}),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler }
  );
}

export async function uploadMixedImport(
  data?: UploadMixedImportBody,
  options: ApiMethodOptions<Contracts.UploadResult, unknown, RequestParams> = {}
): Promise<ApiResult<Contracts.UploadResult>> {
  const { onSuccess, onError, params } = options;

  return handleApiResponse<Contracts.UploadResult, unknown>(
    () => importApi.uploadMixedImportRaw(data as any, params ?? {}),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler }
  );
}
