/* eslint-disable */
/* tslint:disable */
// This file was generated by typedapi-client-helpers. Do not edit manually.

import { ContentType, HttpClient } from "../http-client";
import type { RequestParams } from "../http-client";
import type { ApiResult, ApiMethodOptions } from "typedapi-client-helpers";
import { handleApiResponse } from "typedapi-client-helpers";
import type * as Contracts from "../data-contracts";
import { handleGoodResult as typedApiDefaultSuccessHandler, handleErrors as typedApiDefaultErrorHandler } from "../../utils/defaultApiFunctions";

export interface GetOrdersQuery {
  orderIds?: string[];
  orderNumber?: string;
  productId?: string;
  supplierId?: string;
  minQuantity?: number;
  maxQuantity?: number;
  minTotalPrice?: number;
  maxTotalPrice?: number;
  orderedFrom?: string;
  orderedTo?: string;
  status?: Contracts.OrderStatus;
  statuses?: Contracts.OrderStatus[];
  pageNumber?: number;
  pageSize?: number;
  sortBy?: string;
  sortDirection?: Contracts.SortDirection;
}

export interface CancelOrderQuery {
  reason?: string;
}

export class OrderApi {
  private readonly http: HttpClient;

  constructor(http: HttpClient = new HttpClient()) {
    this.http = http;
  }

  public getOrdersRaw = (
    query?: GetOrdersQuery,
    params: RequestParams = {}
  ): Promise<import("../http-client").HttpResponse<Contracts.OrderModelApiPaginationResponse, unknown>> => {
    return this.http.request<Contracts.OrderModelApiPaginationResponse, unknown>({
      path: "/api/orders",
      method: "GET",
      query: query as any,
      format: "json",
      ...params,
    });
  };

  public createOrderRaw = (
    data?: Contracts.OrderRequest,
    params: RequestParams = {}
  ): Promise<import("../http-client").HttpResponse<Contracts.OrderModel, unknown>> => {
    return this.http.request<Contracts.OrderModel, unknown>({
      path: "/api/orders",
      method: "POST",
      body: data,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  };

  public getOrderByIdRaw = (
    id: string,
    params: RequestParams = {}
  ): Promise<import("../http-client").HttpResponse<Contracts.OrderModel, unknown>> => {
    return this.http.request<Contracts.OrderModel, unknown>({
      path: `/api/orders/${encodeURIComponent(String(id))}`,
      method: "GET",
      format: "json",
      ...params,
    });
  };

  public updateOrderRaw = (
    id: string,
    data?: Contracts.OrderRequest,
    params: RequestParams = {}
  ): Promise<import("../http-client").HttpResponse<Contracts.OrderModel, unknown>> => {
    return this.http.request<Contracts.OrderModel, unknown>({
      path: `/api/orders/${encodeURIComponent(String(id))}`,
      method: "PUT",
      body: data,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  };

  public deleteOrderRaw = (
    id: string,
    params: RequestParams = {}
  ): Promise<import("../http-client").HttpResponse<void, unknown>> => {
    return this.http.request<void, unknown>({
      path: `/api/orders/${encodeURIComponent(String(id))}`,
      method: "DELETE",
      format: "json",
      ...params,
    });
  };

  public approveOrderRaw = (
    id: string,
    params: RequestParams = {}
  ): Promise<import("../http-client").HttpResponse<Contracts.OrderModel, unknown>> => {
    return this.http.request<Contracts.OrderModel, unknown>({
      path: `/api/orders/${encodeURIComponent(String(id))}/approve`,
      method: "POST",
      format: "json",
      ...params,
    });
  };

  public cancelOrderRaw = (
    id: string,
    query?: CancelOrderQuery,
    params: RequestParams = {}
  ): Promise<import("../http-client").HttpResponse<Contracts.OrderModel, unknown>> => {
    return this.http.request<Contracts.OrderModel, unknown>({
      path: `/api/orders/${encodeURIComponent(String(id))}/cancel`,
      method: "POST",
      query: query as any,
      format: "json",
      ...params,
    });
  };
}

const orderApi = new OrderApi();

export async function getOrders(
  query?: GetOrdersQuery,
  options: ApiMethodOptions<Contracts.OrderModelApiPaginationResponse, unknown, RequestParams> = {}
): Promise<ApiResult<Contracts.OrderModelApiPaginationResponse>> {
  const { onSuccess, onError, params } = options;

  return handleApiResponse<Contracts.OrderModelApiPaginationResponse, unknown>(
    () => orderApi.getOrdersRaw(query, params ?? {}),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler }
  );
}

export async function createOrder(
  data?: Contracts.OrderRequest,
  options: ApiMethodOptions<Contracts.OrderModel, unknown, RequestParams> = {}
): Promise<ApiResult<Contracts.OrderModel>> {
  const { onSuccess, onError, params } = options;

  return handleApiResponse<Contracts.OrderModel, unknown>(
    () => orderApi.createOrderRaw(data as any, params ?? {}),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler }
  );
}

export async function getOrderById(
  id: string,
  options: ApiMethodOptions<Contracts.OrderModel, unknown, RequestParams> = {}
): Promise<ApiResult<Contracts.OrderModel>> {
  const { onSuccess, onError, params } = options;

  return handleApiResponse<Contracts.OrderModel, unknown>(
    () => orderApi.getOrderByIdRaw(id, params ?? {}),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler }
  );
}

export async function updateOrder(
  id: string,
  data?: Contracts.OrderRequest,
  options: ApiMethodOptions<Contracts.OrderModel, unknown, RequestParams> = {}
): Promise<ApiResult<Contracts.OrderModel>> {
  const { onSuccess, onError, params } = options;

  return handleApiResponse<Contracts.OrderModel, unknown>(
    () => orderApi.updateOrderRaw(id, data as any, params ?? {}),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler }
  );
}

export async function deleteOrder(
  id: string,
  options: ApiMethodOptions<void, unknown, RequestParams> = {}
): Promise<ApiResult<void>> {
  const { onSuccess, onError, params } = options;

  return handleApiResponse<void, unknown>(
    () => orderApi.deleteOrderRaw(id, params ?? {}),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler }
  );
}

export async function approveOrder(
  id: string,
  options: ApiMethodOptions<Contracts.OrderModel, unknown, RequestParams> = {}
): Promise<ApiResult<Contracts.OrderModel>> {
  const { onSuccess, onError, params } = options;

  return handleApiResponse<Contracts.OrderModel, unknown>(
    () => orderApi.approveOrderRaw(id, params ?? {}),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler }
  );
}

export async function cancelOrder(
  id: string,
  query?: CancelOrderQuery,
  options: ApiMethodOptions<Contracts.OrderModel, unknown, RequestParams> = {}
): Promise<ApiResult<Contracts.OrderModel>> {
  const { onSuccess, onError, params } = options;

  return handleApiResponse<Contracts.OrderModel, unknown>(
    () => orderApi.cancelOrderRaw(id, query, params ?? {}),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler }
  );
}
