/* eslint-disable */
/* tslint:disable */
// This file was generated by typedapi-client-helpers. Do not edit manually.

import { ContentType, HttpClient } from "../http-client";
import type { RequestParams } from "../http-client";
import type { ApiResult, ApiMethodOptions } from "typedapi-client-helpers";
import { handleApiResponse } from "typedapi-client-helpers";
import type * as Contracts from "../data-contracts";
import { handleGoodResult as typedApiDefaultSuccessHandler, handleErrors as typedApiDefaultErrorHandler } from "../../utils/defaultApiFunctions";

export interface GetProductsQuery {
  productIds?: string[];
  search?: string;
  skus?: string[];
  minPrice?: number;
  maxPrice?: number;
  minStock?: number;
  maxStock?: number;
  active?: boolean;
  supplierId?: string;
  createdFrom?: string;
  createdTo?: string;
  pageNumber?: number;
  pageSize?: number;
  sortBy?: string;
  sortDirection?: Contracts.SortDirection;
}

export interface ExportProductsQuery {
  search?: string;
  active?: boolean;
  productIds?: string[];
}

export class ProductApi {
  private readonly http: HttpClient;

  constructor(http: HttpClient = new HttpClient()) {
    this.http = http;
  }

  public getProductsRaw = (
    query?: GetProductsQuery,
    params: RequestParams = {}
  ): Promise<import("../http-client").HttpResponse<Contracts.ProductTableRowApiPaginationResponse, unknown>> => {
    return this.http.request<Contracts.ProductTableRowApiPaginationResponse, unknown>({
      path: "/api/products",
      method: "GET",
      query: query as any,
      format: "json",
      ...params,
    });
  };

  public createProductRaw = (
    data?: Contracts.ProductRequest,
    params: RequestParams = {}
  ): Promise<import("../http-client").HttpResponse<Contracts.ProductModel, unknown>> => {
    return this.http.request<Contracts.ProductModel, unknown>({
      path: "/api/products",
      method: "POST",
      body: data,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  };

  public getProductByIdRaw = (
    id: string,
    params: RequestParams = {}
  ): Promise<import("../http-client").HttpResponse<Contracts.ProductModel, unknown>> => {
    return this.http.request<Contracts.ProductModel, unknown>({
      path: `/api/products/${encodeURIComponent(String(id))}`,
      method: "GET",
      format: "json",
      ...params,
    });
  };

  public updateProductRaw = (
    id: string,
    data?: Contracts.ProductRequest,
    params: RequestParams = {}
  ): Promise<import("../http-client").HttpResponse<Contracts.ProductModel, unknown>> => {
    return this.http.request<Contracts.ProductModel, unknown>({
      path: `/api/products/${encodeURIComponent(String(id))}`,
      method: "PUT",
      body: data,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  };

  public deleteProductRaw = (
    id: string,
    params: RequestParams = {}
  ): Promise<import("../http-client").HttpResponse<void, unknown>> => {
    return this.http.request<void, unknown>({
      path: `/api/products/${encodeURIComponent(String(id))}`,
      method: "DELETE",
      format: "json",
      ...params,
    });
  };

  public toggleProductActiveRaw = (
    id: string,
    params: RequestParams = {}
  ): Promise<import("../http-client").HttpResponse<Contracts.ProductModel, unknown>> => {
    return this.http.request<Contracts.ProductModel, unknown>({
      path: `/api/products/${encodeURIComponent(String(id))}/toggle-active`,
      method: "POST",
      format: "json",
      ...params,
    });
  };

  public exportProductsRaw = (
    query?: ExportProductsQuery,
    params: RequestParams = {}
  ): Promise<import("../http-client").HttpResponse<void, unknown>> => {
    return this.http.request<void, unknown>({
      path: "/api/products/export",
      method: "GET",
      query: query as any,
      format: "json",
      ...params,
    });
  };
}

const productApi = new ProductApi();

export async function getProducts(
  query?: GetProductsQuery,
  options: ApiMethodOptions<Contracts.ProductTableRowApiPaginationResponse, unknown, RequestParams> = {}
): Promise<ApiResult<Contracts.ProductTableRowApiPaginationResponse>> {
  const { onSuccess, onError, params } = options;

  return handleApiResponse<Contracts.ProductTableRowApiPaginationResponse, unknown>(
    () => productApi.getProductsRaw(query, params ?? {}),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler }
  );
}

export async function createProduct(
  data?: Contracts.ProductRequest,
  options: ApiMethodOptions<Contracts.ProductModel, unknown, RequestParams> = {}
): Promise<ApiResult<Contracts.ProductModel>> {
  const { onSuccess, onError, params } = options;

  return handleApiResponse<Contracts.ProductModel, unknown>(
    () => productApi.createProductRaw(data as any, params ?? {}),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler }
  );
}

export async function getProductById(
  id: string,
  options: ApiMethodOptions<Contracts.ProductModel, unknown, RequestParams> = {}
): Promise<ApiResult<Contracts.ProductModel>> {
  const { onSuccess, onError, params } = options;

  return handleApiResponse<Contracts.ProductModel, unknown>(
    () => productApi.getProductByIdRaw(id, params ?? {}),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler }
  );
}

export async function updateProduct(
  id: string,
  data?: Contracts.ProductRequest,
  options: ApiMethodOptions<Contracts.ProductModel, unknown, RequestParams> = {}
): Promise<ApiResult<Contracts.ProductModel>> {
  const { onSuccess, onError, params } = options;

  return handleApiResponse<Contracts.ProductModel, unknown>(
    () => productApi.updateProductRaw(id, data as any, params ?? {}),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler }
  );
}

export async function deleteProduct(
  id: string,
  options: ApiMethodOptions<void, unknown, RequestParams> = {}
): Promise<ApiResult<void>> {
  const { onSuccess, onError, params } = options;

  return handleApiResponse<void, unknown>(
    () => productApi.deleteProductRaw(id, params ?? {}),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler }
  );
}

export async function toggleProductActive(
  id: string,
  options: ApiMethodOptions<Contracts.ProductModel, unknown, RequestParams> = {}
): Promise<ApiResult<Contracts.ProductModel>> {
  const { onSuccess, onError, params } = options;

  return handleApiResponse<Contracts.ProductModel, unknown>(
    () => productApi.toggleProductActiveRaw(id, params ?? {}),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler }
  );
}

export async function exportProducts(
  query?: ExportProductsQuery,
  options: ApiMethodOptions<void, unknown, RequestParams> = {}
): Promise<ApiResult<void>> {
  const { onSuccess, onError, params } = options;

  return handleApiResponse<void, unknown>(
    () => productApi.exportProductsRaw(query, params ?? {}),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler }
  );
}
