/* eslint-disable */
/* tslint:disable */
// This file was generated by typedapi-client-helpers. Do not edit manually.

import { ContentType, HttpClient } from "../http-client";
import type { RequestParams } from "../http-client";
import type { ApiResult, ApiMethodOptions } from "typedapi-client-helpers";
import { handleApiResponse } from "typedapi-client-helpers";
import type * as Contracts from "../data-contracts";
import { handleGoodResult as typedApiDefaultSuccessHandler, handleErrors as typedApiDefaultErrorHandler } from "../../utils/defaultApiFunctions";

export interface GetSuppliersQuery {
  supplierIds?: string[];
  companyName?: string;
  countryCodes?: string[];
  verified?: boolean;
  createdFrom?: string;
  createdTo?: string;
  pageNumber?: number;
  pageSize?: number;
  sortBy?: string;
  sortDirection?: Contracts.SortDirection;
}

export class SupplierApi {
  private readonly http: HttpClient;

  constructor(http: HttpClient = new HttpClient()) {
    this.http = http;
  }

  public getSuppliersRaw = (
    query?: GetSuppliersQuery,
    params: RequestParams = {}
  ): Promise<import("../http-client").HttpResponse<Contracts.SupplierModelApiPaginationResponse, unknown>> => {
    return this.http.request<Contracts.SupplierModelApiPaginationResponse, unknown>({
      path: "/api/suppliers",
      method: "GET",
      query: query as any,
      format: "json",
      ...params,
    });
  };

  public createSupplierRaw = (
    data?: Contracts.SupplierRequest,
    params: RequestParams = {}
  ): Promise<import("../http-client").HttpResponse<Contracts.SupplierModel, unknown>> => {
    return this.http.request<Contracts.SupplierModel, unknown>({
      path: "/api/suppliers",
      method: "POST",
      body: data,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  };

  public getSupplierByIdRaw = (
    id: string,
    params: RequestParams = {}
  ): Promise<import("../http-client").HttpResponse<Contracts.SupplierModel, unknown>> => {
    return this.http.request<Contracts.SupplierModel, unknown>({
      path: `/api/suppliers/${encodeURIComponent(String(id))}`,
      method: "GET",
      format: "json",
      ...params,
    });
  };

  public updateSupplierRaw = (
    id: string,
    data?: Contracts.SupplierRequest,
    params: RequestParams = {}
  ): Promise<import("../http-client").HttpResponse<Contracts.SupplierModel, unknown>> => {
    return this.http.request<Contracts.SupplierModel, unknown>({
      path: `/api/suppliers/${encodeURIComponent(String(id))}`,
      method: "PUT",
      body: data,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  };

  public deleteSupplierRaw = (
    id: string,
    params: RequestParams = {}
  ): Promise<import("../http-client").HttpResponse<void, unknown>> => {
    return this.http.request<void, unknown>({
      path: `/api/suppliers/${encodeURIComponent(String(id))}`,
      method: "DELETE",
      format: "json",
      ...params,
    });
  };

  public verifySupplierRaw = (
    id: string,
    params: RequestParams = {}
  ): Promise<import("../http-client").HttpResponse<Contracts.SupplierModel, unknown>> => {
    return this.http.request<Contracts.SupplierModel, unknown>({
      path: `/api/suppliers/${encodeURIComponent(String(id))}/verify`,
      method: "POST",
      format: "json",
      ...params,
    });
  };
}

const supplierApi = new SupplierApi();

export async function getSuppliers(
  query?: GetSuppliersQuery,
  options: ApiMethodOptions<Contracts.SupplierModelApiPaginationResponse, unknown, RequestParams> = {}
): Promise<ApiResult<Contracts.SupplierModelApiPaginationResponse>> {
  const { onSuccess, onError, params } = options;

  return handleApiResponse<Contracts.SupplierModelApiPaginationResponse, unknown>(
    () => supplierApi.getSuppliersRaw(query, params ?? {}),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler }
  );
}

export async function createSupplier(
  data?: Contracts.SupplierRequest,
  options: ApiMethodOptions<Contracts.SupplierModel, unknown, RequestParams> = {}
): Promise<ApiResult<Contracts.SupplierModel>> {
  const { onSuccess, onError, params } = options;

  return handleApiResponse<Contracts.SupplierModel, unknown>(
    () => supplierApi.createSupplierRaw(data as any, params ?? {}),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler }
  );
}

export async function getSupplierById(
  id: string,
  options: ApiMethodOptions<Contracts.SupplierModel, unknown, RequestParams> = {}
): Promise<ApiResult<Contracts.SupplierModel>> {
  const { onSuccess, onError, params } = options;

  return handleApiResponse<Contracts.SupplierModel, unknown>(
    () => supplierApi.getSupplierByIdRaw(id, params ?? {}),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler }
  );
}

export async function updateSupplier(
  id: string,
  data?: Contracts.SupplierRequest,
  options: ApiMethodOptions<Contracts.SupplierModel, unknown, RequestParams> = {}
): Promise<ApiResult<Contracts.SupplierModel>> {
  const { onSuccess, onError, params } = options;

  return handleApiResponse<Contracts.SupplierModel, unknown>(
    () => supplierApi.updateSupplierRaw(id, data as any, params ?? {}),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler }
  );
}

export async function deleteSupplier(
  id: string,
  options: ApiMethodOptions<void, unknown, RequestParams> = {}
): Promise<ApiResult<void>> {
  const { onSuccess, onError, params } = options;

  return handleApiResponse<void, unknown>(
    () => supplierApi.deleteSupplierRaw(id, params ?? {}),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler }
  );
}

export async function verifySupplier(
  id: string,
  options: ApiMethodOptions<Contracts.SupplierModel, unknown, RequestParams> = {}
): Promise<ApiResult<Contracts.SupplierModel>> {
  const { onSuccess, onError, params } = options;

  return handleApiResponse<Contracts.SupplierModel, unknown>(
    () => supplierApi.verifySupplierRaw(id, params ?? {}),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler }
  );
}
