/* eslint-disable */
/* tslint:disable */
// This file was generated by typedapi-client-helpers. Do not edit manually.

import { ContentType, HttpClient } from "../http-client";
import type { RequestParams } from "../http-client";
import type { ApiResult, ApiMethodOptions } from "typedapi-client-helpers";
import { handleApiResponse } from "typedapi-client-helpers";
import type * as Contracts from "../data-contracts";
import { handleGoodResult as typedApiDefaultSuccessHandler, handleErrors as typedApiDefaultErrorHandler } from "../../utils/defaultApiFunctions";

export interface GetWarehousesQuery {
  search?: string;
  countryCodes?: string[];
  minCapacity?: number;
  maxCapacity?: number;
  isActive?: boolean;
  pageNumber?: number;
  pageSize?: number;
  sortBy?: string;
  sortDirection?: Contracts.SortDirection;
}

export class WarehouseApi {
  private readonly http: HttpClient;

  constructor(http: HttpClient = new HttpClient()) {
    this.http = http;
  }

  public getWarehousesRaw = (
    query?: GetWarehousesQuery,
    params: RequestParams = {}
  ): Promise<import("../http-client").HttpResponse<Contracts.WarehouseModelApiPaginationResponse, unknown>> => {
    return this.http.request<Contracts.WarehouseModelApiPaginationResponse, unknown>({
      path: "/api/warehouses",
      method: "GET",
      query: query as any,
      format: "json",
      ...params,
    });
  };

  public createWarehouseRaw = (
    data?: Contracts.WarehouseRequest,
    params: RequestParams = {}
  ): Promise<import("../http-client").HttpResponse<Contracts.WarehouseModel, unknown>> => {
    return this.http.request<Contracts.WarehouseModel, unknown>({
      path: "/api/warehouses",
      method: "POST",
      body: data,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  };

  public getWarehouseByIdRaw = (
    id: string,
    params: RequestParams = {}
  ): Promise<import("../http-client").HttpResponse<Contracts.WarehouseModel, unknown>> => {
    return this.http.request<Contracts.WarehouseModel, unknown>({
      path: `/api/warehouses/${encodeURIComponent(String(id))}`,
      method: "GET",
      format: "json",
      ...params,
    });
  };

  public updateWarehouseRaw = (
    id: string,
    data?: Contracts.WarehouseRequest,
    params: RequestParams = {}
  ): Promise<import("../http-client").HttpResponse<Contracts.WarehouseModel, unknown>> => {
    return this.http.request<Contracts.WarehouseModel, unknown>({
      path: `/api/warehouses/${encodeURIComponent(String(id))}`,
      method: "PUT",
      body: data,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  };

  public deleteWarehouseRaw = (
    id: string,
    params: RequestParams = {}
  ): Promise<import("../http-client").HttpResponse<void, unknown>> => {
    return this.http.request<void, unknown>({
      path: `/api/warehouses/${encodeURIComponent(String(id))}`,
      method: "DELETE",
      format: "json",
      ...params,
    });
  };
}

const warehouseApi = new WarehouseApi();

export async function getWarehouses(
  query?: GetWarehousesQuery,
  options: ApiMethodOptions<Contracts.WarehouseModelApiPaginationResponse, unknown, RequestParams> = {}
): Promise<ApiResult<Contracts.WarehouseModelApiPaginationResponse>> {
  const { onSuccess, onError, params } = options;

  return handleApiResponse<Contracts.WarehouseModelApiPaginationResponse, unknown>(
    () => warehouseApi.getWarehousesRaw(query, params ?? {}),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler }
  );
}

export async function createWarehouse(
  data?: Contracts.WarehouseRequest,
  options: ApiMethodOptions<Contracts.WarehouseModel, unknown, RequestParams> = {}
): Promise<ApiResult<Contracts.WarehouseModel>> {
  const { onSuccess, onError, params } = options;

  return handleApiResponse<Contracts.WarehouseModel, unknown>(
    () => warehouseApi.createWarehouseRaw(data as any, params ?? {}),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler }
  );
}

export async function getWarehouseById(
  id: string,
  options: ApiMethodOptions<Contracts.WarehouseModel, unknown, RequestParams> = {}
): Promise<ApiResult<Contracts.WarehouseModel>> {
  const { onSuccess, onError, params } = options;

  return handleApiResponse<Contracts.WarehouseModel, unknown>(
    () => warehouseApi.getWarehouseByIdRaw(id, params ?? {}),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler }
  );
}

export async function updateWarehouse(
  id: string,
  data?: Contracts.WarehouseRequest,
  options: ApiMethodOptions<Contracts.WarehouseModel, unknown, RequestParams> = {}
): Promise<ApiResult<Contracts.WarehouseModel>> {
  const { onSuccess, onError, params } = options;

  return handleApiResponse<Contracts.WarehouseModel, unknown>(
    () => warehouseApi.updateWarehouseRaw(id, data as any, params ?? {}),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler }
  );
}

export async function deleteWarehouse(
  id: string,
  options: ApiMethodOptions<void, unknown, RequestParams> = {}
): Promise<ApiResult<void>> {
  const { onSuccess, onError, params } = options;

  return handleApiResponse<void, unknown>(
    () => warehouseApi.deleteWarehouseRaw(id, params ?? {}),
    { onSuccess: onSuccess ?? typedApiDefaultSuccessHandler, onError: onError ?? typedApiDefaultErrorHandler }
  );
}
